const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require(process.env.JSDOM_PATH || 'jsdom');
const main=fs.readFileSync('app-principal.js','utf8'),moduleSource=fs.readFileSync('tg-contract-maintenance.js','utf8');
const fn=name=>main.match(new RegExp('        (?:async )?function '+name+'\\([^]*?\\n        \\}'))[0],plain=v=>JSON.parse(JSON.stringify(v));
function setup(){
 const w=new JSDOM('<div id="modalContratoTitulo"></div><div id="modalContratoCampos"></div><div id="modalContratoOverlay"></div><div id="modalGerarOSCampos"></div><div id="modalGerarOSOverlay"></div><div id="modalRegistoCampos"></div><div id="modalRegistoOverlay"></div><div id="modalHistoricoConteudo"></div>',{runScripts:'outside-only'}).window;
 w.usuarioLogado={id:'a',role:'admin'};w.admin={id:'a',contratosPlano:'anual',contratosExpiracao:Date.now()+86400000,areasNegocio:['seguranca']};
 w.dados={administradores:[w.admin],clientes:[{id:'c',adminId:'a',nome:'Cliente'}],locais:[{id:'l',adminId:'a',clienteId:'c',nome:'Loja'},{id:'b',adminId:'a',clienteId:'c',nome:'Armazém'},{id:'foreign',adminId:'z',clienteId:'c',nome:'SEGREDO'}],equipamentos:[{id:'e1',adminId:'a',clienteId:'c',localId:'l',tipo:'cctv',marca:'Cam'},{id:'e2',adminId:'a',clienteId:'c',localId:'b',tipo:'cctv',marca:'Armazém'},{id:'e3',adminId:'a',clienteId:'c',localId:'l',tipo:'alarme'},{id:'e4',adminId:'a',clienteId:'c',localId:null,tipo:'cctv'},{id:'alien',adminId:'z',clienteId:'c',localId:'l',tipo:'cctv'}],contratos:[],servicos:[],registosManutencao:[],folhasObra:[],funcionarios:[{id:'f',adminId:'a',nome:'Técnico',role:'funcionario'}]};
 w.c={id:'ct',numero:'CT-1',adminId:'a',clienteId:'c',localId:'l',locaisIds:['l','b'],equipamentosIds:['e1','e2','e3'],periodicidade:'anual',tipoIntervencao:'presencial',dataInicio:'2026-01-01',valor:100,gestaoManutencao:{extension:{keep:true},plano:[{id:'cctv-plan',tipo:'cctv',periodicidade:'trimestral',intervencao:'remota',tarefas:[{id:'t1',texto:'Verificar gravações'}]},{id:'alarm-plan',tipo:'alarme',periodicidade:'anual',intervencao:'presencial',tarefas:[{id:'t2',texto:'Testar sensores'}]}],servicos:{maoObra:'incluida'},comercial:{faturacao:'anual',avisoDias:45}}};w.dados.contratos.push(w.c);
 w.PERIODICIDADE_MESES={trimestral:3,semestral:6,anual:12};w.PERIODICIDADE_DIAS={mensal:30,quinzenal:15,semanal:7};w.PERIODICIDADE_LABEL={mensal:'Mensal',trimestral:'Trimestral',semestral:'Semestral',anual:'Anual'};w.EQUIP_TIPOS={cctv:'CCTV',alarme:'Alarme',fire:'Incêndio'};w.adminAtual=()=>w.admin;w.moduloContratosAtivo=()=>w.license!==false;w.tipoExigePresencialAnual=t=>t==='fire';w._clienteLabel=c=>c.nome;w.escapeHtmlSimples=v=>String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');w._preencherDatalistClientes=()=>{};w._ctRenderTiposTrabalho=()=>{};w.aplicarRegrasContrato=()=>{};w._renderGerirTiposEquipCustom=()=>{};w.getDataHoje=()=> '2026-10-10';
 let i=0;w.gerarId=()=> 'new-'+(++i);w.alerts=[];w.alert=x=>w.alerts.push(x);w.confirm=()=>true;w.guardarDados=async()=>{w.saved=true};w.renderizarTudo=()=>{};w.abrirSecao=()=>{};w.fecharModalContrato=()=>{};w.gerarNumeroContrato=()=> 'CT-2';w._algumEquipExigePresencialAnual=()=>false;w._ctTiposTrabalhoSelecionados=()=>[];w._snap={};
 w.eval('var contratoEditandoId=null,_ctEquipamentosAtuais=[],gerarOSContratoId=null,registoContratoId=null;'+['_contratoLocalIds','_contratoAbrangeLocal','_contratoInstalacoes','_contratoInstalacoesLabel','_contratoEquipamentos','_ctEquipamentosDisponiveis','_ctAdicionarTodosEquipamentos','_contratoOpcoesInstalacao','_ctRenderCobertura','_ctCoberturaChange','onClienteContratoChange','onLocalContratoChange','_atualizarSelectEquipDisponivel','onEquipAddContratoChange','_renderListaEquipContrato','_equipStrContrato','abrirModalContrato','salvarContrato','addDias','addMeses','avancarPeriodicidade','calcularProximaManutencao','ultimoRegistoContrato','abrirGerarOSContrato','abrirModalRegisto','salvarRegisto'].map(fn).join('\n'));
 w.eval(moduleSource);return w;
}
test('complete contract form restores plans, included services and commercial terms across four tabs',async()=>{const w=setup();try{
 w.c.locaisIds=['l'];w.c.equipamentosIds=['e1','e3'];
 w.abrirModalContrato('ct');assert.equal(w.document.querySelectorAll('[data-ct-tab]').length,4);assert.equal(w.document.querySelectorAll('[data-ct-system]').length,2);assert.equal(w.document.getElementById('ct_labor').value,'incluida');assert.equal(w.document.getElementById('ct_faturacao').value,'anual');
 w.document.querySelector('[data-ct-tab="plano"]').click();assert.equal(w.document.getElementById('ct_plano_extra').hidden,false);assert.equal(w.document.querySelector('[data-ct-system="cctv"] [data-period]').value,'trimestral');w.document.querySelector('[data-ct-system="cctv"] textarea').value='Verificar gravações\nLimpar lentes';
 w.document.getElementById('ct_visitas').value='4';w.document.getElementById('ct_pagamento').value='30';await w.salvarContrato();assert.equal(w.saved,true);assert.equal(w.c.gestaoManutencao.servicos.visitasAno,4);assert.equal(w.c.gestaoManutencao.comercial.prazoPagamento,30);assert.deepEqual(plain(w.c.gestaoManutencao.extension),{keep:true});assert.equal(w.c.gestaoManutencao.plano[0].tarefas[0].id,'t1');assert.equal(w.c.gestaoManutencao.plano[0].tarefas.length,2);
 w.abrirModalContrato('ct');assert.equal(w.document.getElementById('ct_visitas').value,'4');assert.equal(w.document.querySelector('[data-ct-system="cctv"] textarea').value,'Verificar gravações\nLimpar lentes');
}finally{w.close()}});
test('equipment picker and Add all include only the chosen installation',()=>{const w=setup();try{
 w.c.equipamentosIds=['e1'];w.abrirModalContrato('ct');assert(!w.document.querySelector('#ct_equip_add option[value="e2"]'));assert(!w.document.querySelector('#ct_equip_add option[value="alien"]'));assert(!w.document.querySelector('#ct_equip_add option[value="e4"]'));w._ctAdicionarTodosEquipamentos();assert.equal(w.document.querySelectorAll('#ct_equip_lista > span').length,2);
 w.document.getElementById('ct_local').value='b';w.onLocalContratoChange();assert(w.document.querySelector('#ct_equip_add option[value="e2"]'));assert.deepEqual([...w.document.querySelectorAll('.ct-local-chk:checked')].map(x=>x.value),['b']);
}finally{w.close()}});
test('each site and system advances independently, legacy records remain supported',()=>{const w=setup();try{
 w.dados.registosManutencao.push({id:'reg',adminId:'a',contratoId:'ct',localId:'l',dataRealizacao:'2026-09-01',sistemasIds:['cctv-plan']});const rows=w.TGContractMaintenance.schedule(w.c);
 assert.equal(rows.find(s=>s.localId==='l'&&s.plan.tipo==='cctv').data,'2026-12-01');assert.equal(rows.find(s=>s.localId==='b').data,'2026-04-01');assert.equal(rows.find(s=>s.plan.tipo==='alarme').data,'2027-01-01');assert.equal(w.calcularProximaManutencao(w.c),'2026-04-01');assert.deepEqual(plain(w.TGContractMaintenance.due(w.c,'l','2026-10-10')),[]);
 w.dados.registosManutencao[0].sistemasIds=['alarm-plan'];assert.equal(w.TGContractMaintenance.schedule(w.c).find(s=>s.localId==='l'&&s.plan.tipo==='cctv').data,'2026-04-01');
}finally{w.close()}});
test('OS picks valid systems at the chosen site and snapshots immutable tasks without commercial data',()=>{const w=setup();try{
 w.abrirGerarOSContrato('ct');const picker=w.document.getElementById('ct_os_planos');assert.equal(picker.querySelectorAll('input').length,2);assert.deepEqual(plain(w.TGContractMaintenance.selectedOS(w.c,'l')),['cctv-plan']);
 const os={id:'os',localId:'l'};w.TGContractMaintenance.snapshot(os,w.c,['cctv-plan']);assert.deepEqual(plain(os.planoManutencao.equipamentosIds),['e1']);assert.equal(os.planoManutencao.tarefas[0].texto,'CCTV — Verificar gravações');assert(!JSON.stringify(os).includes('faturacao'));w.c.gestaoManutencao.plano[0].tarefas[0].texto='Nova tarefa';assert.equal(os.planoManutencao.tarefas[0].texto,'CCTV — Verificar gravações');
 assert.equal(w.TGContractMaintenance.checklist(os,{obrasChecklistItens:[{id:'global',texto:'EPI'},{id:'disabled',ativo:false}]}).length,2);
 w.document.getElementById('os_gerar_local').value='b';w.document.getElementById('os_gerar_local').dispatchEvent(new w.Event('change'));assert.equal(picker.querySelectorAll('input').length,1);picker.querySelector('input').checked=false;assert.throws(()=>w.TGContractMaintenance.selectedOS(w.c,'b'),/Seleciona/);assert.throws(()=>w.TGContractMaintenance.snapshot({localId:'b'},w.c,['alarm-plan']),/Sem sistemas/);
}finally{w.close()}});
test('services limits, negative values and expiry before start are rejected before saving',()=>{const w=setup();try{
 w.abrirModalContrato('ct');w.document.getElementById('ct_labor').value='limitada';assert.throws(()=>w.TGContractMaintenance.collect(),/limite de horas/);w.document.getElementById('ct_horas').value='10';w.document.getElementById('ct_viagens').value='limitadas';assert.throws(()=>w.TGContractMaintenance.collect(),/zona/);w.document.getElementById('ct_zona').value='Lisboa';w.document.getElementById('ct_material').value='parcial';assert.throws(()=>w.TGContractMaintenance.collect(),/materiais/);w.document.getElementById('ct_srv_notas').value='Cabos';assert.equal(w.TGContractMaintenance.collect().servicos.horasAno,10);
 w.document.getElementById('ct_valor').value='-1';assert.throws(()=>w.TGContractMaintenance.collect(),/valor/);w.document.getElementById('ct_valor').value='100';w.document.getElementById('ct_validade').value='2025-01-01';assert.throws(()=>w.TGContractMaintenance.collect(),/validade/);
}finally{w.close()}});
test('commercial expiry reminder follows the chosen notice and does not modify renewal dates',()=>{const w=setup();try{
 w.c.validadeContrato='2026-11-20';assert.equal(w.TGContractMaintenance.alerts(w.c,'2026-10-10').dias,41);assert.equal(w.TGContractMaintenance.alerts(w.c,'2026-09-01'),null);assert.equal(w.TGContractMaintenance.alerts(w.c,'2026-12-01').dias,-11);assert.equal(w.c.validadeContrato,'2026-11-20');
}finally{w.close()}});
test('archive history reuses original sheets, filters ownership and leaves snapshots clean; failures permit retry',async()=>{const w=setup();try{
 const query=table=>({table,filters:[],select(){return this},eq(k,v){this.filters.push([k,v]);return this},in(k,v){this.filters.push([k,v]);return this},order(){return this}});w.supa={from:query};const calls=[];
 const rows={servicos:[{id:'old-os',admin_id:'a',cliente_id:'c',contrato_id:'ct',local_id:'b',data:'2020-01-01',numero_registo:'OLD',descricao:'Intervenção antiga'},{id:'alien',admin_id:'z',cliente_id:'c',contrato_id:'ct',descricao:'SEGREDO'}],registos_manutencao:[],folhas_obra:[{id:'old-sheet',admin_id:'a',servico_id:'old-os',data:'2020-01-01',descricao:'Folha original'}]};
 w._buscarPaginadoGenerico=async q=>{calls.push(q);return {data:rows[q.table],error:null}};
 const keys=['servicos','registosManutencao','folhasObra'];w.isoToMs=v=>v;w.msToISO=v=>v;w.nn=v=>v||null;w.hhmm=v=>v;w.eval('window.M={'+keys.map(key=>{const i=main.indexOf('            '+key+': {',main.indexOf('const M ='));return main.slice(i,main.indexOf('\n            },',i)+15)}).join('\n')+'};');
 w.abrirFolhaDetalhe=id=>w.opened=id;w.gerarPDFFolha=(id,t)=>w.pdf=[id,t];w.abrirVerOS=id=>w.openedOS=id;
 await w.TGContractMaintenance.history('ct');assert(w.document.body.textContent.includes('OLD'));assert(!w.document.body.textContent.includes('SEGREDO'));assert.equal(w.saved,undefined);assert.equal(w._snap.folhasObra.get('old-sheet'),JSON.stringify(w.M.folhasObra.to(w.dados.folhasObra[0])));assert(calls.every(q=>q.filters.some(([k,v])=>k==='admin_id'&&v==='a')));w.document.querySelector('[data-contract-sheet]').click();assert.equal(w.opened,'old-sheet');w.document.querySelector('[data-contract-pdf]').click();assert.deepEqual(w.pdf,['old-sheet','cliente']);
 w._buscarPaginadoGenerico=async()=>({data:[],error:Error('offline')});await w.TGContractMaintenance.history('ct');assert(w.document.querySelector('[data-contract-retry]'));assert(w.document.body.textContent.includes('Folha original'));w.usuarioLogado={id:'f',adminId:'a',role:'funcionario'};w.opened=null;w.document.querySelector('[data-contract-sheet]').click();assert.equal(w.opened,null);
}finally{w.close()}});
test('explicit Sede maintenance advances only Sede and unfinished task snapshots do not complete maintenance',()=>{const w=setup();try{
 w.c.locaisIds.push('');w.c.equipamentosIds.push('e4');w.dados.registosManutencao.push({id:'sede',adminId:'a',contratoId:'ct',localId:null,dataRealizacao:'2026-09-01',sistemasIds:['cctv-plan']});const rows=w.TGContractMaintenance.schedule(w.c);assert.equal(rows.find(s=>s.localId==='').data,'2026-12-01');assert.equal(rows.find(s=>s.localId==='l'&&s.plan.tipo==='cctv').data,'2026-04-01');
 const os={planoManutencao:{tarefas:[{id:'task'}]},checklist:{}};assert.equal(w.TGContractMaintenance.completedTasks(os),false);os.checklist.task=true;assert.equal(w.TGContractMaintenance.completedTasks(os),true);
}finally{w.close()}});
test('configuration and immutable OS tasks round-trip through database mappers, old records omit new fields',()=>{const w=setup();try{
 w.isoToMs=v=>v;w.msToISO=v=>v;w.nn=v=>v||null;w.hhmm=v=>v;
 w.eval('window.M={'+['contratos','servicos','registosManutencao'].map(key=>{const i=main.indexOf('            '+key+': {',main.indexOf('const M ='));return main.slice(i,main.indexOf('\n            },',i)+15)}).join('\n')+'};');
 for(const [key,db,app,value] of [['contratos','gestao_manutencao','gestaoManutencao',w.c.gestaoManutencao],['servicos','plano_manutencao','planoManutencao',{tarefas:[{id:'t',texto:'Original'}]}],['registosManutencao','sistemas_ids','sistemasIds',['cctv-plan']]]){assert(!Object.hasOwn(w.M[key].to(w.M[key].from({id:'legacy'})),db));assert.deepEqual(plain(w.M[key].to(w.M[key].from({id:'new',[db]:value}))[db]),plain(value));}
}finally{w.close()}});
test('new contracts can define system plans before creating the installation, and equipment can choose a semiannual maintenance schedule',()=>{const w=setup();try{
 w.abrirModalContrato('ct');w.dados.equipamentos.push({id:'pending',adminId:'a',clienteId:'c',localId:'__novo__',tipo:'fire'});w.eval("_ctEquipamentosAtuais=['pending'];");w.document.getElementById('ct_local').value='__novo__';w.document.querySelectorAll('.ct-local-chk').forEach(c=>c.checked=false);w.TGContractMaintenance.refreshPlan();const row=w.document.querySelector('[data-ct-system="fire"]');assert(row);assert.equal(row.querySelector('[data-period]').value,'anual');assert.equal(row.querySelector('[data-period]').disabled,false);row.querySelector('[data-period]').value='semestral';assert.equal(row.querySelector('[data-intervention]').value,'presencial');assert.equal(w.TGContractMaintenance.collect().plano[0].tipo,'fire');
}finally{w.close()}});
test('manual maintenance stores exactly the systems and site chosen, while other sites remain due',()=>{const w=setup();try{
 w._notificarFuncionario=()=>{};w.fecharModalRegisto=()=>{};w.abrirModalRegisto('ct');w.document.getElementById('rg_local').value='b';w.document.getElementById('rg_local').dispatchEvent(new w.Event('change'));w.salvarRegisto();assert.equal(w.dados.registosManutencao.length,1);assert.deepEqual(plain(w.dados.registosManutencao[0].sistemasIds),['cctv-plan']);assert.equal(w.dados.registosManutencao[0].localId,'b');assert.equal(w.dados.folhasObra[0].localId,'b');assert.equal(w.calcularProximaManutencao(w.c),'2026-04-01');
}finally{w.close()}});
function emptyHistory(w){w.supa={from:()=>({select(){return this},eq(){return this},in(){return this},order(){return this}})};w._buscarPaginadoGenerico=async()=>({data:[],error:null});}
test('maintenance alerts follow each site and system, configured thresholds and license ownership',()=>{const w=setup();try{
 w.c.dataInicio='2025-11-01';let rows=w.TGContractMaintenance.maintenanceRows('c');assert.equal(rows.length,3);assert.equal(rows.find(r=>r.plan.tipo==='alarme').state,'A vencer');assert(rows.filter(r=>r.plan.tipo==='cctv').every(r=>r.state==='Em atraso'));
 w.c.gestaoManutencao.alertas={avisoDias:25,urgenteDias:23};rows=w.TGContractMaintenance.maintenanceRows('c');assert.equal(rows.find(r=>r.plan.tipo==='alarme').state,'Urgente');assert(w.TGContractMaintenance.maintenanceHTML('c').includes('Criar OS para as selecionadas'));
 w.c.gestaoManutencao.alertas.avisoDias=10;assert.equal(w.TGContractMaintenance.maintenanceRows('c').length,2);assert.equal(w.TGContractMaintenance.maintenanceRows('other').length,0);w.dados.contratos.push({...w.c,id:'alien',adminId:'z'});assert.equal(w.TGContractMaintenance.maintenanceRows().length,2);
 w.license=false;assert.equal(w.TGContractMaintenance.maintenanceHTML(), '');w.license=true;w.usuarioLogado.role='funcionario';assert.equal(w.TGContractMaintenance.maintenanceHTML(), '');
}finally{w.close()}});
test('open OS suppresses creation only for its covered systems and installation; cancellation reopens the action',()=>{const w=setup();try{
 w.c.dataInicio='2025-11-01';const os={id:'open',numeroRegisto:'OS-123',adminId:'a',clienteId:'c',contratoId:'ct',localId:'l',status:'pendente',planoManutencao:{sistemasIds:['cctv-plan']}};w.dados.servicos.push(os);const rows=w.TGContractMaintenance.maintenanceRows();assert.equal(rows.filter(r=>r.os).length,1);assert.equal(rows.find(r=>r.os).state,'OS agendada');assert(w.TGContractMaintenance.maintenanceHTML().includes('Ver OS'));assert.equal(w.TGContractMaintenance.pendingOS(w.c,'b','cctv-plan'),undefined);assert.equal(w.TGContractMaintenance.pendingOS(w.c,'l','alarm-plan'),undefined);
 delete os.planoManutencao;assert.equal(w.TGContractMaintenance.pendingOS(w.c,'l','alarm-plan'),os);os.status='cancelado';assert.equal(w.TGContractMaintenance.pendingOS(w.c,'l','cctv-plan'),undefined);os.status='concluído';assert.equal(w.TGContractMaintenance.pendingOS(w.c,'l','cctv-plan'),undefined);
}finally{w.close()}});
test('alert action preselects an upcoming system and groups only selected systems at the same site',async()=>{const w=setup();try{
 emptyHistory(w);w.c.dataInicio='2025-11-01';const host=w.document.createElement('div');host.innerHTML=w.TGContractMaintenance.maintenanceHTML('c');w.document.body.append(host);const group=host.querySelector('[data-maint-local="l"]');group.querySelector('[data-maint-action="create"][data-maint-system="alarm-plan"]').click();await new Promise(r=>setTimeout(r,0));assert.equal(w.document.getElementById('os_gerar_local').value,'l');assert.deepEqual(plain(w.TGContractMaintenance.selectedOS(w.c,'l')),['alarm-plan']);
 group.querySelectorAll('.ct-maint-select').forEach(c=>c.checked=true);group.querySelector('[data-maint-action="group"]').click();await new Promise(r=>setTimeout(r,0));assert.deepEqual(plain(w.TGContractMaintenance.selectedOS(w.c,'l')),['cctv-plan','alarm-plan']);assert.equal(w.document.getElementById('os_gerar_local').value,'l');
}finally{w.close()}});
test('availability blocks archived open orders, failed verification and expired contracts',async()=>{const w=setup();try{
 emptyHistory(w);await w.TGContractMaintenance.availability(w.c,'l',['cctv-plan']);w.dados.servicos.push({id:'old',numeroRegisto:'OLD',adminId:'a',clienteId:'c',contratoId:'ct',localId:'l',status:'pendente',planoManutencao:{sistemasIds:['cctv-plan']}});await assert.rejects(w.TGContractMaintenance.availability(w.c,'l',['cctv-plan']),/OLD/);await w.TGContractMaintenance.availability(w.c,'b',['cctv-plan']);w._buscarPaginadoGenerico=async()=>({data:[],error:Error('offline')});await assert.rejects(w.TGContractMaintenance.availability(w.c,'b',['cctv-plan']),/confirmar as OS/);w.c.validadeContrato='2026-10-01';await assert.rejects(w.TGContractMaintenance.availability(w.c,'b',['cctv-plan']),/validade/);const html=w.TGContractMaintenance.maintenanceHTML();assert(!html.includes('data-maint-action="create"'));assert(html.includes('Contrato expirado'));
}finally{w.close()}});
test('maintenance notice settings persist and reject an urgent threshold outside the notice window',async()=>{const w=setup();try{
 w.c.locaisIds=['l'];w.c.equipamentosIds=['e1','e3'];
 w.abrirModalContrato('ct');assert.equal(w.document.getElementById('ct_alerta_dias').value,'30');assert.equal(w.document.getElementById('ct_urgente_dias').value,'7');w.document.getElementById('ct_alerta_dias').value='20';w.document.getElementById('ct_urgente_dias').value='21';assert.throws(()=>w.TGContractMaintenance.collect(),/urgente/);w.document.getElementById('ct_urgente_dias').value='5';await w.salvarContrato();assert.deepEqual(plain(w.c.gestaoManutencao.alertas),{avisoDias:20,urgenteDias:5});
}finally{w.close()}});
test('maintenance alerts live inside Alerts and Pending and never create a dashboard or agenda section',()=>{const w=setup();try{
 for(const id of ['dashboardCentralConteudo','agendaConteudo','homeAgendaWrap','alertasPendencias','homeAlertas']){const el=w.document.createElement('div');el.id=id;w.document.body.append(el)}w.TGContractMaintenance.renderMaintenance();w.document.dispatchEvent(new w.Event('tg:interface-updated'));assert.equal(w.document.querySelectorAll('#alertasPendencias [data-maint-alert-host]').length,1);assert(w.document.getElementById('alertasPendencias').textContent.includes('Em atraso'));assert.equal(w.document.querySelectorAll('#tg_maintenance_dashboard,#tg_maintenance_agenda,#tg_maintenance_home').length,0);w.dados.registosManutencao.push({adminId:'a',contratoId:'ct',localId:'b',dataRealizacao:'2026-10-10',sistemasIds:['cctv-plan']});w.document.dispatchEvent(new w.Event('tg:interface-updated'));assert(!w.document.getElementById('alertasPendencias').textContent.includes('Armazém'));
}finally{w.close()}});
test('server status refresh releases a closed OS and preserves unsynchronized local edits',async()=>{const w=setup();try{
 emptyHistory(w);w.M={servicos:{from:r=>r,to:r=>r}};let remote={id:'archived',numeroRegisto:'OLD',adminId:'a',clienteId:'c',contratoId:'ct',localId:'l',status:'pendente',planoManutencao:{sistemasIds:['cctv-plan']}};w._buscarPaginadoGenerico=async q=>({data:q===undefined?[]:[],error:null});w.supa={from:table=>({table,select(){return this},eq(){return this},in(){return this},order(){return this}})};w._buscarPaginadoGenerico=async q=>({data:q.table==='servicos'?[remote]:[],error:null});await assert.rejects(w.TGContractMaintenance.availability(w.c,'l',['cctv-plan']),/OLD/);remote={...remote,status:'concluído'};await w.TGContractMaintenance.availability(w.c,'l',['cctv-plan']);assert.equal(w.dados.servicos[0].status,'concluído');w.dados.servicos[0].descricao='local edit';remote={...remote,descricao:'server edit'};await w.TGContractMaintenance.availability(w.c,'l',['cctv-plan']);assert.equal(w.dados.servicos[0].descricao,'local edit');
}finally{w.close()}});
test('OS creation holds its lock until synchronization finishes and reports a pending sync accurately',async()=>{const w=setup();try{
 emptyHistory(w);w.eval(fn('confirmarGerarOS'));w.fecharGerarOS=()=>{};w._horaMin=v=>{const [h,m]=v.split(':').map(Number);return h*60+m};w.gerarNumeroRegistoServidor=async()=> 'OS-1';w.abrirGerarOSContrato('ct');w.document.querySelector('.os-gerar-func-chk').checked=true;w.document.getElementById('os_hora').value='';let release;w.guardarDados=()=>new Promise(r=>release=r);const first=w.confirmarGerarOS();await new Promise(r=>setTimeout(r,0));assert.equal(w.dados.servicos.length,1);await w.confirmarGerarOS();assert.equal(w.dados.servicos.length,1);assert.equal(w.confirmarGerarOS.emCurso,true);release();await first;assert.equal(w.confirmarGerarOS.emCurso,false);
 w.dados.servicos[0].status='concluído';w.guardarDados=async()=>{throw Error('offline')};await w.confirmarGerarOS();assert.equal(w.dados.servicos.length,2);assert(w.alerts.at(-1).includes('neste dispositivo'));assert.equal(w.confirmarGerarOS.emCurso,false);
}finally{w.close()}});

test('both web and installed-app entry pages load the same maintenance and passport versions after the main app',()=>{
 const index=fs.readFileSync('index.html','utf8'),login=fs.readFileSync('login.html','utf8'),sw=fs.readFileSync('sw.js','utf8');
 const scripts=html=>[...html.matchAll(/<script[^>]+src="([^"]+)"/g)].map(m=>m[1]);
 for(const name of ['app-principal.js','tg-equipment-reports.js','tg-contract-maintenance.js','tg-passport.js']){
  const a=scripts(index).filter(s=>s.startsWith(name+'?')),b=scripts(login).filter(s=>s.startsWith(name+'?'));
  assert.equal(a.length,1);assert.deepEqual(b,a);assert(sw.includes('./'+a[0]));
 }
 for(const html of [index,login]){const names=scripts(html);assert(names.findIndex(s=>s.startsWith('tg-contract-maintenance.js?'))>names.findIndex(s=>s.startsWith('app-principal.js?')));}
 for(const name of ['_wsResumoHtml','_wsContratosHtml'])assert(fn(name).includes('tg_maintenance_customer'));
});

test('changing installation clears selected equipment and plans without altering saved ownership or history',()=>{const w=setup();try{
 w.abrirModalContrato('ct');assert.deepEqual(plain(w.eval('_ctEquipamentosAtuais')),['e1','e3']);
 w.document.getElementById('ct_local').value='b';w.onLocalContratoChange();assert.deepEqual(plain(w.eval('_ctEquipamentosAtuais')),[]);assert.equal(w.document.querySelectorAll('[data-ct-equipment]').length,0);assert.equal(w.TGContractMaintenance.collect().plano.length,0);
 w._ctAdicionarTodosEquipamentos();assert.deepEqual(plain(w.eval('_ctEquipamentosAtuais')),['e2']);assert.equal(w.document.querySelector('[data-ct-equipment]').dataset.ctEquipment,'e2');
 w.document.querySelector('.ct-local-chk[value="l"]').checked=true;w._ctCoberturaChange();assert.equal(w.document.getElementById('ct_local').value,'l');assert.deepEqual(plain(w.eval('_ctEquipamentosAtuais')),[]);
 assert.deepEqual(plain(w.c.equipamentosIds),['e1','e2','e3']);assert.equal(w.dados.equipamentos.find(e=>e.id==='e2').localId,'b');
}finally{w.close()}});
test('same-type equipment has independent periodicity, alerts, tasks and OS snapshots',()=>{const w=setup();try{
 w.dados.equipamentos.push({id:'e5',adminId:'a',clienteId:'c',localId:'l',tipo:'cctv',marca:'Second'});w.c.locaisIds=['l'];w.c.equipamentosIds=['e1','e5'];w.c.dataInicio='2026-01-01';w.abrirModalContrato('ct');
 const first=w.document.querySelector('[data-ct-equipment="e1"]'),second=w.document.querySelector('[data-ct-equipment="e5"]');assert(first&&second);first.querySelector('[data-period]').value='mensal';first.querySelector('[data-next]').value='2026-01-31';second.querySelector('[data-period]').value='semestral';second.querySelector('[data-next]').value='2026-07-01';first.querySelector('textarea').value='First task';second.querySelector('textarea').value='Second task';
 w.c.gestaoManutencao=w.TGContractMaintenance.collect();const [a,b]=w.c.gestaoManutencao.plano;assert.notEqual(a.id,b.id);assert.equal(a.equipamentoId,'e1');assert.equal(b.equipamentoId,'e5');
 let rows=w.TGContractMaintenance.schedule(w.c);assert.equal(rows.find(r=>r.plan.id===a.id).data,'2026-01-31');assert.equal(rows.find(r=>r.plan.id===b.id).data,'2026-07-01');
 const os={id:'selected-os',adminId:'a',clienteId:'c',contratoId:'ct',localId:'l'};w.TGContractMaintenance.snapshot(os,w.c,[a.id]);assert.deepEqual(plain(os.planoManutencao.equipamentosIds),['e1']);assert.equal(os.planoManutencao.tarefas.length,1);assert.equal(os.planoManutencao.tarefas[0].equipamentoId,'e1');assert(w.TGContractMaintenance.maintenanceHTML('c').includes('Second'));
 w.dados.registosManutencao.push({id:'reg',adminId:'a',contratoId:'ct',localId:'l',dataRealizacao:'2026-10-10',sistemasIds:[a.id]});rows=w.TGContractMaintenance.schedule(w.c);assert.equal(rows.find(r=>r.plan.id===a.id).data,'2026-11-09');assert.equal(rows.find(r=>r.plan.id===b.id).data,'2026-07-01');
 w.c.gestaoManutencao.plano[0].tarefas[0].texto='Changed';assert(os.planoManutencao.tarefas[0].texto.includes('First task'));
}finally{w.close()}});
test('editing a legacy system plan inherits its original maintenance and open OS without conflating new equipment plans',()=>{const w=setup();try{
 w.c.locaisIds=['l'];w.c.equipamentosIds=['e1'];w.dados.registosManutencao.push({id:'old',adminId:'a',contratoId:'ct',localId:'l',dataRealizacao:'2026-09-01',sistemasIds:['cctv-plan']});w.dados.servicos.push({id:'old-os',adminId:'a',clienteId:'c',contratoId:'ct',localId:'l',status:'pendente',planoManutencao:{sistemasIds:['cctv-plan']}});
 w.abrirModalContrato('ct');w.c.gestaoManutencao=w.TGContractMaintenance.collect();const p=w.c.gestaoManutencao.plano[0];assert.equal(p.origemSistemaId,'cctv-plan');assert.equal(w.TGContractMaintenance.schedule(w.c)[0].data,'2026-12-01');assert.equal(w.TGContractMaintenance.pendingOS(w.c,'l',p.id).id,'old-os');
}finally{w.close()}});
test('equipment maintenance metadata overrides old contract grouping and advances only the completed equipment',()=>{const w=setup();try{
 w.c.locaisIds=['l'];w.c.equipamentosIds=['e1','e3'];const cam=w.dados.equipamentos.find(e=>e.id==='e1'),alarm=w.dados.equipamentos.find(e=>e.id==='e3');cam.fichaTecnica={manutencao:{periodicidade:'anual',proximaData:'2027-02-01'}};alarm.fichaTecnica={manutencao:{periodicidade:'semestral',proximaData:'2026-12-01'}};
 let rows=w.TGContractMaintenance.schedule(w.c);assert.equal(rows.find(r=>r.plan.equipamentoId==='e1').data,'2027-02-01');assert.equal(rows.find(r=>r.plan.equipamentoId==='e3').data,'2026-12-01');const p=rows.find(r=>r.plan.equipamentoId==='e3').plan;w.dados.registosManutencao.push({id:'reg',adminId:'a',contratoId:'ct',localId:'l',dataRealizacao:'2026-12-01',sistemasIds:[p.id]});rows=w.TGContractMaintenance.schedule(w.c);assert.equal(rows.find(r=>r.plan.equipamentoId==='e3').data,'2027-06-01');assert.equal(rows.find(r=>r.plan.equipamentoId==='e1').data,'2027-02-01');
 w.abrirModalContrato('ct');const row=w.document.querySelector('[data-ct-equipment="e3"]');assert.equal(row.querySelector('[data-period]').value,'semestral');row.querySelector('[data-period]').value='mensal';w.TGContractMaintenance.refreshPlan();assert.equal(w.document.querySelector('[data-ct-equipment="e3"] [data-period]').value,'mensal');w.TGContractMaintenance.collect();assert.equal(alarm.fichaTecnica.manutencao.periodicidade,'mensal');const next=w.TGContractMaintenance.schedule({...w.c,gestaoManutencao:w.TGContractMaintenance.collect()}).find(r=>r.plan.equipamentoId==='e3');assert.equal(next.plan.id,p.id);
}finally{w.close()}});
