const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require(process.env.JSDOM_PATH || 'jsdom');
const main=fs.readFileSync('app-principal.js','utf8'),moduleSource=fs.readFileSync('tg-contract-maintenance.js','utf8');
const fn=name=>main.match(new RegExp('        (?:async )?function '+name+'\\([^]*?\\n        \\}'))[0],plain=v=>JSON.parse(JSON.stringify(v));
function setup(){
 const w=new JSDOM('<div id="modalContratoTitulo"></div><div id="modalContratoCampos"></div><div id="modalContratoOverlay"></div><div id="modalGerarOSCampos"></div><div id="modalGerarOSOverlay"></div><div id="modalRegistoCampos"></div><div id="modalRegistoOverlay"></div><div id="modalHistoricoConteudo"></div>',{runScripts:'outside-only'}).window;
 w.usuarioLogado={id:'a',role:'admin'};w.admin={id:'a',contratosPlano:'anual',contratosExpiracao:Date.now()+86400000,areasNegocio:['seguranca']};
 w.dados={administradores:[w.admin],clientes:[{id:'c',adminId:'a',nome:'Cliente'}],locais:[{id:'l',adminId:'a',clienteId:'c',nome:'Loja'},{id:'b',adminId:'a',clienteId:'c',nome:'Armazém'},{id:'foreign',adminId:'z',clienteId:'c',nome:'SEGREDO'}],equipamentos:[{id:'e1',adminId:'a',clienteId:'c',localId:'l',tipo:'cctv',marca:'Cam'},{id:'e2',adminId:'a',clienteId:'c',localId:'b',tipo:'cctv',marca:'Armazém'},{id:'e3',adminId:'a',clienteId:'c',localId:'l',tipo:'alarme'},{id:'e4',adminId:'a',clienteId:'c',localId:null,tipo:'cctv'},{id:'alien',adminId:'z',clienteId:'c',localId:'l',tipo:'cctv'}],contratos:[],servicos:[],registosManutencao:[],folhasObra:[],funcionarios:[{id:'f',adminId:'a',nome:'Técnico',role:'funcionario'}]};
 w.c={id:'ct',numero:'CT-1',adminId:'a',clienteId:'c',localId:'l',locaisIds:['l','b'],equipamentosIds:['e1','e2','e3'],periodicidade:'anual',tipoIntervencao:'presencial',dataInicio:'2026-01-01',valor:100,gestaoManutencao:{extension:{keep:true},plano:[{id:'cctv-plan',tipo:'cctv',periodicidade:'trimestral',intervencao:'remota',tarefas:[{id:'t1',texto:'Verificar gravações'}]},{id:'alarm-plan',tipo:'alarme',periodicidade:'anual',intervencao:'presencial',tarefas:[{id:'t2',texto:'Testar sensores'}]}],servicos:{maoObra:'incluida'},comercial:{faturacao:'anual',avisoDias:45}}};w.dados.contratos.push(w.c);
 w.PERIODICIDADE_MESES={trimestral:3,semestral:6,anual:12};w.PERIODICIDADE_DIAS={mensal:30,quinzenal:15,semanal:7};w.PERIODICIDADE_LABEL={mensal:'Mensal',trimestral:'Trimestral',semestral:'Semestral',anual:'Anual'};w.EQUIP_TIPOS={cctv:'CCTV',alarme:'Alarme',fire:'Incêndio'};w.adminAtual=()=>w.admin;w.moduloContratosAtivo=()=>w.license!==false;w.tipoExigePresencialAnual=t=>t==='fire';w._clienteLabel=c=>c.nome;w.escapeHtmlSimples=v=>String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');w._preencherDatalistClientes=()=>{};w._ctRenderTiposTrabalho=()=>{};w.aplicarRegrasContrato=()=>{};w._renderGerirTiposEquipCustom=()=>{};w.getDataHoje=()=> '2026-10-10';
 let i=0;w.gerarId=()=> 'new-'+(++i);w.alerts=[];w.alert=x=>w.alerts.push(x);w.confirm=()=>true;w.guardarDados=async()=>{w.saved=true};w.renderizarTudo=()=>{};w.abrirSecao=()=>{};w.fecharModalContrato=()=>{};w.gerarNumeroContrato=()=> 'CT-2';w._algumEquipExigePresencialAnual=()=>false;w._ctTiposTrabalhoSelecionados=()=>[];w._snap={};
 w.eval('var contratoEditandoId=null,_ctEquipamentosAtuais=[],gerarOSContratoId=null,registoContratoId=null;'+['_contratoLocalIds','_contratoAbrangeLocal','_contratoInstalacoes','_contratoInstalacoesLabel','_contratoEquipamentos','_ctEquipamentosDisponiveis','_ctAdicionarTodosEquipamentos','_contratoOpcoesInstalacao','_ctRenderCobertura','_ctCoberturaChange','onClienteContratoChange','onLocalContratoChange','_atualizarSelectEquipDisponivel','onEquipAddContratoChange','_renderListaEquipContrato','_equipStrContrato','abrirModalContrato','salvarContrato','addDias','addMeses','avancarPeriodicidade','calcularProximaManutencao','ultimoRegistoContrato','abrirGerarOSContrato','abrirModalRegisto','salvarRegisto'].map(fn).join('\n'));
 w.eval(moduleSource);return w;
}
test('complete contract form restores plans, included services and commercial terms across four tabs',async()=>{const w=setup();try{
 w.abrirModalContrato('ct');assert.equal(w.document.querySelectorAll('[data-ct-tab]').length,4);assert.equal(w.document.querySelectorAll('[data-ct-system]').length,2);assert.equal(w.document.getElementById('ct_labor').value,'incluida');assert.equal(w.document.getElementById('ct_faturacao').value,'anual');
 w.document.querySelector('[data-ct-tab="plano"]').click();assert.equal(w.document.getElementById('ct_plano_extra').hidden,false);assert.equal(w.document.querySelector('[data-ct-system="cctv"] [data-period]').value,'trimestral');w.document.querySelector('[data-ct-system="cctv"] textarea').value='Verificar gravações\nLimpar lentes';
 w.document.getElementById('ct_visitas').value='4';w.document.getElementById('ct_pagamento').value='30';await w.salvarContrato();assert.equal(w.saved,true);assert.equal(w.c.gestaoManutencao.servicos.visitasAno,4);assert.equal(w.c.gestaoManutencao.comercial.prazoPagamento,30);assert.deepEqual(plain(w.c.gestaoManutencao.extension),{keep:true});assert.equal(w.c.gestaoManutencao.plano[0].tarefas[0].id,'t1');assert.equal(w.c.gestaoManutencao.plano[0].tarefas.length,2);
 w.abrirModalContrato('ct');assert.equal(w.document.getElementById('ct_visitas').value,'4');assert.equal(w.document.querySelector('[data-ct-system="cctv"] textarea').value,'Verificar gravações\nLimpar lentes');
}finally{w.close()}});
test('equipment selection spans covered installations, Add all excludes foreign tenants and Sede without coverage',()=>{const w=setup();try{
 w.c.equipamentosIds=['e1'];w.abrirModalContrato('ct');assert(w.document.querySelector('#ct_equip_add option[value="e2"]'));assert(!w.document.querySelector('#ct_equip_add option[value="alien"]'));assert(!w.document.querySelector('#ct_equip_add option[value="e4"]'));w._ctAdicionarTodosEquipamentos();assert.equal(w.document.querySelectorAll('#ct_equip_lista > span').length,3);
 w.document.querySelector('.ct-local-chk[value="b"]').checked=false;w._ctCoberturaChange();assert(!w.document.querySelector('#ct_equip_add option[value="e2"]'));assert.equal(w.TGContractMaintenance.collect().plano.length,2);
}finally{w.close()}});
test('each site and system advances independently, legacy records remain supported',()=>{const w=setup();try{
 w.dados.registosManutencao.push({id:'reg',adminId:'a',contratoId:'ct',localId:'l',dataRealizacao:'2026-09-01',sistemasIds:['cctv-plan']});const rows=w.TGContractMaintenance.schedule(w.c);
 assert.equal(rows.find(s=>s.localId==='l'&&s.plan.tipo==='cctv').data,'2026-12-01');assert.equal(rows.find(s=>s.localId==='b').data,'2026-04-01');assert.equal(rows.find(s=>s.plan.tipo==='alarme').data,'2027-01-01');assert.equal(w.calcularProximaManutencao(w.c),'2026-04-01');assert.deepEqual(plain(w.TGContractMaintenance.due(w.c,'l','2026-10-10')),[]);
 w.dados.registosManutencao[0].sistemasIds=['alarm-plan'];assert.equal(w.TGContractMaintenance.schedule(w.c).find(s=>s.localId==='l'&&s.plan.tipo==='cctv').data,'2026-04-01');
}finally{w.close()}});
test('OS picks valid systems at the chosen site and snapshots immutable tasks without commercial data',()=>{const w=setup();try{
 w.abrirGerarOSContrato('ct');const picker=w.document.getElementById('ct_os_planos');assert.equal(picker.querySelectorAll('input').length,2);assert.deepEqual(plain(w.TGContractMaintenance.selectedOS(w.c,'l')),['cctv-plan']);
 const os={id:'os',localId:'l'};w.TGContractMaintenance.snapshot(os,w.c,['cctv-plan']);assert.deepEqual(plain(os.planoManutencao.equipamentosIds),['e1']);assert.equal(os.planoManutencao.tarefas[0].texto,'CCTV — Verificar gravações');assert(!JSON.stringify(os).includes('faturacao'));w.c.gestaoManutencao.plano[0].tarefas[0].texto='Nova tarefa';assert.equal(os.planoManutencao.tarefas[0].texto,'CCTV — Verificar gravações');
 assert.equal(w.TGContractMaintenance.checklist(os,{obrasChecklistItens:[{id:'global',texto:'EPI'},{id:'disabled',ativo:false}]}).length,2);
 w.document.getElementById('os_gerar_local').value='b';w.document.getElementById('os_gerar_local').dispatchEvent(new w.Event('change'));assert.equal(picker.querySelectorAll('input').length,1);picker.querySelector('input').checked=false;assert.throws(()=>w.TGContractMaintenance.selectedOS(w.c,'b'),/Seleciona/);assert.throws(()=>w.TGContractMaintenance.snapshot({localId:'b'},w.c,['alarm-plan']),/Sem sistemas/);
}finally{w.close()}});
test('services limits, negative values and expiry before start are rejected before saving',()=>{const w=setup();try{
 w.abrirModalContrato('ct');w.document.getElementById('ct_labor').value='limitada';assert.throws(()=>w.TGContractMaintenance.collect(),/limite de horas/);w.document.getElementById('ct_horas').value='10';w.document.getElementById('ct_viagens').value='limitadas';assert.throws(()=>w.TGContractMaintenance.collect(),/zona/);w.document.getElementById('ct_zona').value='Lisboa';w.document.getElementById('ct_material').value='parcial';assert.throws(()=>w.TGContractMaintenance.collect(),/materiais/);w.document.getElementById('ct_srv_notas').value='Cabos';assert.equal(w.TGContractMaintenance.collect().servicos.horasAno,10);
 w.document.getElementById('ct_valor').value='-1';assert.throws(()=>w.TGContractMaintenance.collect(),/valor/);w.document.getElementById('ct_valor').value='100';w.document.getElementById('ct_validade').value='2025-01-01';assert.throws(()=>w.TGContractMaintenance.collect(),/validade/);
}finally{w.close()}});
test('commercial expiry reminder follows the chosen notice and does not modify renewal dates',()=>{const w=setup();try{
 w.c.validadeContrato='2026-11-20';assert.equal(w.TGContractMaintenance.alerts(w.c,'2026-10-10').dias,41);assert.equal(w.TGContractMaintenance.alerts(w.c,'2026-09-01'),null);assert.equal(w.TGContractMaintenance.alerts(w.c,'2026-12-01').dias,-11);assert.equal(w.c.validadeContrato,'2026-11-20');
}finally{w.close()}});
test('archive history reuses original sheets, filters ownership and leaves snapshots clean; failures permit retry',async()=>{const w=setup();try{
 const query=table=>({table,filters:[],select(){return this},eq(k,v){this.filters.push([k,v]);return this},in(k,v){this.filters.push([k,v]);return this},order(){return this}});w.supa={from:query};const calls=[];
 const rows={servicos:[{id:'old-os',admin_id:'a',cliente_id:'c',contrato_id:'ct',local_id:'b',data:'2020-01-01',numero_registo:'OLD',descricao:'Intervenção antiga'},{id:'alien',admin_id:'z',cliente_id:'c',contrato_id:'ct',descricao:'SEGREDO'}],registos_manutencao:[],folhas_obra:[{id:'old-sheet',admin_id:'a',servico_id:'old-os',data:'2020-01-01',descricao:'Folha original'}]};
 w._buscarPaginadoGenerico=async q=>{calls.push(q);return {data:rows[q.table],error:null}};
 const keys=['servicos','registosManutencao','folhasObra'];w.isoToMs=v=>v;w.msToISO=v=>v;w.nn=v=>v||null;w.hhmm=v=>v;w.eval('window.M={'+keys.map(key=>{const i=main.indexOf('            '+key+': {',main.indexOf('const M ='));return main.slice(i,main.indexOf('\n            },',i)+15)}).join('\n')+'};');
 w.abrirFolhaDetalhe=id=>w.opened=id;w.gerarPDFFolha=(id,t)=>w.pdf=[id,t];w.abrirVerOS=id=>w.openedOS=id;
 await w.TGContractMaintenance.history('ct');assert(w.document.body.textContent.includes('OLD'));assert(!w.document.body.textContent.includes('SEGREDO'));assert.equal(w.saved,undefined);assert.equal(w._snap.folhasObra.get('old-sheet'),JSON.stringify(w.M.folhasObra.to(w.dados.folhasObra[0])));assert(calls.every(q=>q.filters.some(([k,v])=>k==='admin_id'&&v==='a')));w.document.querySelector('[data-contract-sheet]').click();assert.equal(w.opened,'old-sheet');w.document.querySelector('[data-contract-pdf]').click();assert.deepEqual(w.pdf,['old-sheet','cliente']);
 w._buscarPaginadoGenerico=async()=>({data:[],error:Error('offline')});await w.TGContractMaintenance.history('ct');assert(w.document.querySelector('[data-contract-retry]'));assert(w.document.body.textContent.includes('Folha original'));w.usuarioLogado={id:'f',adminId:'a',role:'funcionario'};w.opened=null;w.document.querySelector('[data-contract-sheet]').click();assert.equal(w.opened,null);
}finally{w.close()}});
test('explicit Sede maintenance advances only Sede and unfinished task snapshots do not complete maintenance',()=>{const w=setup();try{
 w.c.locaisIds.push('');w.c.equipamentosIds.push('e4');w.dados.registosManutencao.push({id:'sede',adminId:'a',contratoId:'ct',localId:null,dataRealizacao:'2026-09-01',sistemasIds:['cctv-plan']});const rows=w.TGContractMaintenance.schedule(w.c);assert.equal(rows.find(s=>s.localId==='').data,'2026-12-01');assert.equal(rows.find(s=>s.localId==='l'&&s.plan.tipo==='cctv').data,'2026-04-01');
 const os={planoManutencao:{tarefas:[{id:'task'}]},checklist:{}};assert.equal(w.TGContractMaintenance.completedTasks(os),false);os.checklist.task=true;assert.equal(w.TGContractMaintenance.completedTasks(os),true);
}finally{w.close()}});
test('configuration and immutable OS tasks round-trip through database mappers, old records omit new fields',()=>{const w=setup();try{
 w.isoToMs=v=>v;w.msToISO=v=>v;w.nn=v=>v||null;w.hhmm=v=>v;
 w.eval('window.M={'+['contratos','servicos','registosManutencao'].map(key=>{const i=main.indexOf('            '+key+': {',main.indexOf('const M ='));return main.slice(i,main.indexOf('\n            },',i)+15)}).join('\n')+'};');
 for(const [key,db,app,value] of [['contratos','gestao_manutencao','gestaoManutencao',w.c.gestaoManutencao],['servicos','plano_manutencao','planoManutencao',{tarefas:[{id:'t',texto:'Original'}]}],['registosManutencao','sistemas_ids','sistemasIds',['cctv-plan']]]){assert(!Object.hasOwn(w.M[key].to(w.M[key].from({id:'legacy'})),db));assert.deepEqual(plain(w.M[key].to(w.M[key].from({id:'new',[db]:value}))[db]),plain(value));}
}finally{w.close()}});
test('new contracts can define system plans before creating the installation, and restricted systems retain annual onsite rules',()=>{const w=setup();try{
 w.abrirModalContrato('ct');w.dados.equipamentos.push({id:'pending',adminId:'a',clienteId:'c',localId:'__novo__',tipo:'fire'});w.eval("_ctEquipamentosAtuais=['pending'];");w.document.getElementById('ct_local').value='__novo__';w.document.querySelectorAll('.ct-local-chk').forEach(c=>c.checked=false);w.TGContractMaintenance.refreshPlan();const row=w.document.querySelector('[data-ct-system="fire"]');assert(row);assert.equal(row.querySelector('[data-period]').value,'anual');assert.equal(row.querySelector('[data-period]').disabled,true);assert.equal(row.querySelector('[data-intervention]').value,'presencial');assert.equal(w.TGContractMaintenance.collect().plano[0].tipo,'fire');
}finally{w.close()}});
test('manual maintenance stores exactly the systems and site chosen, while other sites remain due',()=>{const w=setup();try{
 w._notificarFuncionario=()=>{};w.fecharModalRegisto=()=>{};w.abrirModalRegisto('ct');w.document.getElementById('rg_local').value='b';w.document.getElementById('rg_local').dispatchEvent(new w.Event('change'));w.salvarRegisto();assert.equal(w.dados.registosManutencao.length,1);assert.deepEqual(plain(w.dados.registosManutencao[0].sistemasIds),['cctv-plan']);assert.equal(w.dados.registosManutencao[0].localId,'b');assert.equal(w.dados.folhasObra[0].localId,'b');assert.equal(w.calcularProximaManutencao(w.c),'2026-04-01');
}finally{w.close()}});
