const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const main=fs.readFileSync('app-principal.js','utf8'),helper=fs.readFileSync('tg-equipment-reports.js','utf8');
const fn=n=>main.match(new RegExp('        (?:async )?function '+n+'\\([^]*?\\n        \\}'))[0],plain=x=>JSON.parse(JSON.stringify(x));
function setup(){const w=new JSDOM('<body></body>',{runScripts:'outside-only'}).window;w.dados={servicos:[],equipamentos:[],relatoriosEspecialidade:[]};w.usuarioLogado={id:'a',role:'admin'};w.alert=()=>{};w.eval(helper);return w;}
test('two equipment with the same specialty require separate signed reports; no-report equipment stays excluded',()=>{const w=setup();try{
 const os={id:'os',adminId:'a',tiposTrabalho:['REX','RCCTV'],planoManutencao:{sistemasIds:['cctv']}};const eq=[{id:'e1',tipo:'cctv',fichaTecnica:{nome:'NVR 1',relatorioEspecialidade:'RCCTV'}},{id:'e2',tipo:'cctv',fichaTecnica:{nome:'NVR 2',relatorioEspecialidade:'RCCTV'}},{id:'e3',fichaTecnica:{relatorioEspecialidade:''}}];w.TGEquipmentReports.snapshot(os,eq);w.dados.servicos.push(os);assert.equal(w.TGEquipmentReports.pending(os).length,2);assert.deepEqual(plain(os.tiposTrabalho),['RCCTV']);assert.deepEqual(plain(os.planoManutencao.sistemasIds),['cctv']);
 w.dados.relatoriosEspecialidade.push({id:'r1',adminId:'a',servicoId:'os',tipo:'RCCTV',campos:{equipamentoId:'e1'},rascunho:false});assert.deepEqual(plain(w.TGEquipmentReports.pending(os).map(r=>r.equipamentoId)),['e2']);w.dados.relatoriosEspecialidade.push({adminId:'a',servicoId:'os',tipo:'RCCTV',campos:{equipamentoId:'e2'},rascunho:true});assert.equal(w.TGEquipmentReports.pending(os).length,1);w.dados.relatoriosEspecialidade[1].rascunho=false;assert.equal(w.TGEquipmentReports.pending(os).length,0);
 eq[0].fichaTecnica.nome='Changed';eq[0].fichaTecnica.relatorioEspecialidade='';assert.equal(os.planoManutencao.relatoriosEquipamentos[0].equipamentoNome,'NVR 1');
}finally{w.close()}});
test('reports from another tenant or without an equipment link cannot satisfy a new equipment-specific OS',()=>{const w=setup();try{
 const os={id:'os',adminId:'a'};w.TGEquipmentReports.snapshot(os,[{id:'e',fichaTecnica:{relatorioEspecialidade:'REX'}}]);w.dados.relatoriosEspecialidade=[{adminId:'z',servicoId:'os',tipo:'REX',campos:{equipamentoId:'e'}},{adminId:'a',servicoId:'os',tipo:'REX',campos:{}}];assert.equal(w.TGEquipmentReports.pending(os).length,1);assert.equal(w.TGEquipmentReports.resolve(os,'REX','other'),undefined);
 const old={id:'old',adminId:'a',tiposTrabalho:['REX']};w.dados.relatoriosEspecialidade.push({adminId:'a',servicoId:'old',tipo:'REX',campos:{}});assert.equal(w.TGEquipmentReports.pending(old).length,0);w.TGEquipmentReports.snapshot(os,[{id:'e',fichaTecnica:{relatorioEspecialidade:''}}]);assert.equal(w.TGEquipmentReports.pending(os).length,0);
}finally{w.close()}});
test('equipment selector requires an explicit specialty or Sem relatório and restricts edits to its tenant',()=>{const w=setup();try{
 assert.throws(()=>w.TGEquipmentReports.validate('__choose__'),/Indica/);assert.equal(w.TGEquipmentReports.validate(''),'');w.dados.equipamentos=[{id:'e',adminId:'a'},{id:'foreign',adminId:'z'}];for(const eq of w.dados.equipamentos)w.document.body.insertAdjacentHTML('beforeend',w.TGEquipmentReports.equipmentField(eq));const select=w.document.querySelector('[data-equipment-report="e"]');select.value='REX';select.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(w.dados.equipamentos[0].fichaTecnica.relatorioEspecialidade,'REX');const foreign=w.document.querySelector('[data-equipment-report="foreign"]');foreign.value='REX';foreign.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(w.dados.equipamentos[1].fichaTecnica,undefined);w.usuarioLogado.role='funcionario';select.value='RBI';select.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(w.dados.equipamentos[0].fichaTecnica.relatorioEspecialidade,'REX');
}finally{w.close()}});
test('completion queue handles each equipment and stops when only a draft was saved',()=>{const w=setup();try{
 const os={id:'os',adminId:'a'};w.TGEquipmentReports.snapshot(os,[{id:'e1',fichaTecnica:{relatorioEspecialidade:'REX'}},{id:'e2',fichaTecnica:{relatorioEspecialidade:'REX'}}]);w.dados.servicos.push(os);w.eval(fn('_tiposEspecialidadePendentes')+'\n'+fn('abrirFilaRelatoriosEspecialidade'));assert.deepEqual(plain(w._tiposEspecialidadePendentes('os')),['REX','REX']);let opened,done=false;w._abrirModalRelatorioEspecialidade=(id,tipo,cb,equipmentId)=>{opened={id,tipo,cb,equipmentId}};w.abrirFilaRelatoriosEspecialidade('os',['REX'],()=>done=true);assert.equal(opened.equipmentId,'e1');opened.cb();assert.equal(done,false);assert.equal(opened.equipmentId,'e1');w.dados.relatoriosEspecialidade.push({adminId:'a',servicoId:'os',tipo:'REX',campos:{equipamentoId:'e1'}});opened.cb();assert.equal(opened.equipmentId,'e2');assert.equal(done,false);w.dados.relatoriosEspecialidade.push({adminId:'a',servicoId:'os',tipo:'REX',campos:{equipamentoId:'e2'}});opened.cb();assert.equal(done,true);
}finally{w.close()}});
test('equipment references and choices round-trip through existing JSON columns',()=>{const w=setup();try{
 w.isoToMs=v=>v;w.msToISO=v=>v;w.nn=v=>v||null;w.hhmm=v=>v;w.eval('window.M={'+['equipamentos','servicos','relatoriosEspecialidade'].map(key=>{const i=main.indexOf('            '+key+': {',main.indexOf('const M ='));return main.slice(i,main.indexOf('\n            },',i)+15)}).join('\n')+'};');for(const [key,column,value] of [['equipamentos','ficha_tecnica',{relatorioEspecialidade:'REX'}],['servicos','plano_manutencao',{relatoriosEquipamentos:[{equipamentoId:'e',tipo:'REX'}]}],['relatoriosEspecialidade','campos',{equipamentoId:'e',htmlSnapshot:'saved'}]])assert.deepEqual(plain(w.M[key].to(w.M[key].from({id:'id',[column]:value}))[column]),value);
}finally{w.close()}});
function fullFixture(file){const src=fs.readFileSync(file,'utf8');const w=new Function('require','process',src.slice(0,src.indexOf('\ntest('))+'\nreturn setup();')(require,process);w.eval(helper);return w;}
const flush=()=>new Promise(r=>setTimeout(r,15));
test('passport equipment creation refuses an unspecified report and saves an explicit Sem relatório choice',async()=>{const w=fullFixture('tests/passport.test.cjs');try{
 await w.TGPassport.open('c','l');w.document.querySelector('[data-pp-action="edit-equipment"]').click();const form=w.document.querySelector('[data-pp-editor] form');form.elements.nome.value='NVR novo';const n=w.dados.equipamentos.length;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(w.dados.equipamentos.length,n);form.elements.relatorioEspecialidade.value='';form.elements.manutencaoPeriodicidade.value='anual';form.elements.manutencaoProxima.value='2027-01-01';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(w.dados.equipamentos.length,n+1);assert.equal(w.dados.equipamentos.at(-1).fichaTecnica.relatorioEspecialidade,'');
}finally{w.close()}});
test('maintenance snapshot captures only selected equipment reports and advances after both reports and the original worksheet',()=>{const w=fullFixture('tests/contract-maintenance.test.cjs');try{
 w.dados.relatoriosEspecialidade=[];w.dados.equipamentos[0].fichaTecnica={relatorioEspecialidade:'RCCTV',nome:'NVR 1'};w.dados.equipamentos.push({id:'extra',adminId:'a',clienteId:'c',localId:'l',tipo:'cctv',fichaTecnica:{relatorioEspecialidade:'RCCTV',nome:'NVR 2'}});w.c.equipamentosIds.push('extra');w.dados.equipamentos.find(e=>e.id==='e3').fichaTecnica={relatorioEspecialidade:'RIN'};const os={id:'os',adminId:'a',clienteId:'c',contratoId:'ct',localId:'l',tiposTrabalho:['REX']};w.TGContractMaintenance.snapshot(os,w.c,['cctv-plan']);assert.equal(w.TGEquipmentReports.requirements(os).length,2);assert.deepEqual(plain(os.tiposTrabalho),['RCCTV']);const sheet={adminId:'a',servicoId:'os',data:'2026-10-10'};os.checklist=Object.fromEntries(os.planoManutencao.tarefas.map(t=>[t.id,true]));assert.equal(w.TGContractMaintenance.registerMaintenance(os,sheet),false);for(const equipamentoId of ['e1','extra'])w.dados.relatoriosEspecialidade.push({adminId:'a',servicoId:'os',tipo:'RCCTV',campos:{equipamentoId}});assert.equal(w.TGContractMaintenance.registerMaintenance(os,sheet),true);assert.equal(w.TGContractMaintenance.registerMaintenance(os,sheet),false);assert.equal(w.dados.registosManutencao.length,1);assert.deepEqual(plain(w.dados.registosManutencao[0].sistemasIds),['cctv-plan']);assert.equal(w.TGContractMaintenance.schedule(w.c).find(r=>r.localId==='l'&&r.plan.tipo==='cctv').data,'2027-01-10');assert.equal(w.TGContractMaintenance.schedule(w.c).find(r=>r.localId==='b').data,'2026-04-01');
}finally{w.close()}});
test('actual report editor saves separate drafts and completing one equipment preserves the other draft',async()=>{const w=setup();try{
 const os={id:'os',adminId:'a',clienteId:'c',localId:'l'};w.TGEquipmentReports.snapshot(os,[{id:'e1',fichaTecnica:{relatorioEspecialidade:'RCCTV',nome:'NVR 1'}},{id:'e2',fichaTecnica:{relatorioEspecialidade:'RCCTV',nome:'NVR 2'}}]);w.dados.servicos.push(os);w.dados.clientes=[{id:'c',nome:'Cliente'}];w.dados.administradores=[{id:'a'}];w.dados.contratos=[];w.REPORT_TYPE_DEFS={RCCTV:{nome:'CCTV'}};w.REPORT_TEMPLATES={RCCTV:'<html><body><input id="foo"></body></html>'};w.getDataHoje=()=> '2026-10-10';w.prompt=()=>null;w._tenantId=()=> 'a';w._numeroSeqPreview=()=>1;w.proximoNumeroRelatorio=async()=>1;w._uploadTextoStorage=async()=>false;w._uploadImagemStorage=async()=>false;w.guardarDados=async()=>{};w.escapeHtmlSimples=v=>String(v??'');w.obterNomeFuncionario=()=> 'Técnico';let n=0;w.gerarId=()=> 'new-'+(++n);w.eval('var _relEspecOnMessageAtual=null;'+fn('_abrirModalRelatorioEspecialidade'));
 async function open(id){const result=w._abrirModalRelatorioEspecialidade('os','RCCTV',()=>{},id);const frame=w.document.getElementById('re_iframe');frame.dispatchEvent(new w.Event('load'));await result;return frame;}
 let frame=await open('e1');w.dispatchEvent(new w.MessageEvent('message',{source:frame.contentWindow,data:{type:'relatorioEspecialidadeRascunho',html:'<html><body>draft 1</body></html>'}}));await flush();assert.equal(w.dados.relatoriosEspecialidade[0].campos.equipamentoId,'e1');frame=await open('e2');w.dispatchEvent(new w.MessageEvent('message',{source:frame.contentWindow,data:{type:'relatorioEspecialidadeRascunho',html:'<html><body>draft 2</body></html>'}}));await flush();assert.equal(w.dados.relatoriosEspecialidade.length,2);frame=await open('e2');w.dispatchEvent(new w.MessageEvent('message',{source:frame.contentWindow,data:{type:'relatorioEspecialidadeConcluido',html:'<html><body>signed</body></html>'}}));await flush();assert.equal(w.dados.relatoriosEspecialidade.length,2);assert(w.dados.relatoriosEspecialidade.find(r=>r.campos.equipamentoId==='e1').rascunho);const done=w.dados.relatoriosEspecialidade.find(r=>r.campos.equipamentoId==='e2');assert(!done.rascunho);assert(done.campos.htmlSnapshot.includes('NVR 2'));assert.deepEqual(plain(w.TGEquipmentReports.pending(os).map(r=>r.equipamentoId)),['e1']);
}finally{w.close()}});
test('an existing equipment with no report choice blocks a new OS instead of silently disabling the report',()=>{const w=setup();try{
 const os={id:'os',adminId:'a'};assert.throws(()=>w.TGEquipmentReports.snapshot(os,[{id:'e',marca:'NVR sem configuração'}]),/NVR sem configuração/);assert.equal(os.planoManutencao,undefined);
}finally{w.close()}});
test('equipment creation requires its own frequency and date, supports semiannual fire and supports a compressed photograph',async()=>{const w=fullFixture('tests/passport.test.cjs');try{
 await w.TGPassport.open('c','l');w.document.querySelector('[data-pp-action="edit-equipment"]').click();const form=w.document.querySelector('form');assert(form.elements.foto);assert(form.querySelector('[data-pp-photo-menu]'));form.elements.nome.value='Central incêndio';form.elements.tipo.value='incendio';form.elements.relatorioEspecialidade.value='RSI';const n=w.dados.equipamentos.length;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(w.dados.equipamentos.length,n);form.elements.manutencaoPeriodicidade.value='semestral';form.elements.manutencaoProxima.value='2027-04-10';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await flush();const e=w.dados.equipamentos.at(-1);assert.equal(e.fichaTecnica.manutencao.periodicidade,'semestral');assert.equal(e.fichaTecnica.manutencao.proximaData,'2027-04-10');assert.equal(e.fichaTecnica.foto,'');
 w.document.querySelector('[data-pp-action="equipment"][data-pp-id="'+e.id+'"]').click();assert(w.document.querySelector('[data-pp-editor]').textContent.includes('Semestral'));
}finally{w.close()}});
test('single photograph menu captures or uploads an equipment image and saves it with its maintenance settings',async()=>{const w=fullFixture('tests/passport.test.cjs');try{
 await w.TGPassport.open('c','l');w.document.querySelector('[data-pp-action="edit-equipment"]').click();const form=w.document.querySelector('form'),menu=form.querySelector('[data-pp-photo-menu]');assert.equal(menu.querySelector('summary').textContent,'Carregar fotografia');const camera=form.querySelector('[data-pp-photo-file="camera"]'),gallery=form.querySelector('[data-pp-photo-file="gallery"]');let chosen='';camera.click=()=>chosen='camera';gallery.click=()=>chosen='gallery';menu.open=true;form.querySelector('[data-pp-photo-choice="camera"]').click();assert.equal(chosen,'camera');assert.equal(menu.open,false);form.querySelector('[data-pp-photo-choice="gallery"]').click();assert.equal(chosen,'gallery');
 w._comprimirImagem=async()=> 'data:image/jpeg;base64,'+'A'.repeat(1000);w.uploadDataURL=async()=> 'https://example.com/installed.jpg';Object.defineProperty(camera,'files',{value:[new w.File(['photo'],'camera.jpg',{type:'image/jpeg'})]});camera.dispatchEvent(new w.Event('change'));await flush();assert(form.querySelector('[data-pp-photo-preview] img'));form.elements.nome.value='Câmara instalada';form.elements.relatorioEspecialidade.value='RCCTV';form.elements.manutencaoPeriodicidade.value='anual';form.elements.manutencaoProxima.value='2027-10-10';form.dispatchEvent(new w.Event('submit',{cancelable:true,bubbles:true}));await flush();const e=w.dados.equipamentos.at(-1);assert.equal(e.fichaTecnica.foto,'https://example.com/installed.jpg');assert.equal(e.fichaTecnica.manutencao.periodicidade,'anual');assert(w.document.querySelector('[data-pp-action="equipment"][data-pp-id="'+e.id+'"] img'));
}finally{w.close()}});
