const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {JSDOM}=require(process.env.JSDOM_PATH || 'jsdom');
const main=fs.readFileSync('app-principal.js','utf8'),moduleSource=fs.readFileSync('tg-passport.js','utf8');
const mappingSource=['clientes','locais','equipamentos','servicos','folhasObra'].map(key=>{const start=main.indexOf('            '+key+': {',main.indexOf('const M ='));return main.slice(start,main.indexOf('\n            },',start)+15);}).join('\n');
function setup(){
 const dom=new JSDOM('<div id="wsClienteOverlay" class="open" data-cliente-atual="c"><div id="wsClienteConteudo"></div></div>',{url:'https://totalgest.example/login.html',runScripts:'outside-only'}),w=dom.window;
 w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=()=>{};w.alerts=[];w.alert=v=>w.alerts.push(v);w.usuarioLogado={id:'a',role:'admin',nome:'Técnico Teste'};w._wsAbaAtual='locais';w.licensed=true;w.contracts=true;w._licencaValidaTenant=()=>w.licensed;w.admin={packAtual:'expert'};w.adminDoUtilizador=()=>w.admin;w.moduloContratosAtivo=()=>w.contracts;
 w.dados={clientes:[{id:'c',adminId:'a',nome:'Cliente Teste',morada:'Rua Teste',passaporteTecnico:{notas:'Notas sede'}},{id:'other',adminId:'b',nome:'Outro cliente'}],locais:[{id:'l',clienteId:'c',adminId:'a',nome:'Armazém',morada:'Rua Armazém',passaporteTecnico:{armario:'Piso 0',notas:'Notas do local',documentos:[{nome:'Esquema',url:'https://example.com/esquema.pdf'}]}},{id:'foreign',clienteId:'other',adminId:'b',nome:'SEGREDO'}],equipamentos:[{id:'e',adminId:'a',localId:'l',tipo:'cctv',marca:'Marca',observacoes:'Nota antiga',fichaTecnica:{nome:'Câmara 03',ip:'192.168.1.3',porta:'Switch PoE / 3',estado:'avaria'}},{id:'shared',adminId:'a',localId:null,tipo:'rede'},{id:'unrelated',adminId:'a',localId:null,tipo:'cctv'},{id:'foreign-e',adminId:'b',localId:'l',tipo:'cctv'}],contratos:[{id:'ct',adminId:'a',clienteId:'c',localId:'l',equipamentosIds:['shared']}],funcionarios:[],servicos:[{id:'live',adminId:'a',clienteId:'c',localId:'l',funcionarioId:'f',funcionariosIds:['f'],descricao:'Avaria',data:'2026-10-08',status:'pendente',checklist:{A:true},fotos:[{url:'https://example.com/foto.jpg'}]}]};
 w.eval("var msToISO=ms=>ms==null?null:new Date(Number(ms)).toISOString(),isoToMs=iso=>iso==null?null:Date.parse(iso),nn=v=>(v===''||v===undefined)?null:v,hhmm=t=>t?String(t).slice(0,5):null;window.M={\n"+mappingSource+'\n};');
 w._snap={servicos:new Map()};w._snap.servicos.set('live',JSON.stringify(w.M.servicos.to(w.dados.servicos[0])));
 w.calls=[];const q={select(v){w.calls.push(['select',v]);return this},eq(k,v){w.calls.push(['eq',k,v]);return this},order(k,v){w.calls.push(['order',k,v]);return this}};w.supa={from:t=>{w.queryTable=t;w.calls.push(['from',t]);return q}};
 w.archive=[{id:'old',admin_id:'a',cliente_id:'c',local_id:'l',numero_registo:'OLD-1',data:'2020-01-01',descricao:'Manutenção antiga',status:'concluído',checklist:{OLD:true},fotos:[]}];w.archiveSheets=[];w._buscarPaginadoGenerico=async()=>({data:w.queryTable==='folhas_obra'?w.archiveSheets:w.archive,error:null});w.abrirFolhaDetalhe=async id=>w.openedSheet=id;w.gerarPDFFolha=async(id,type)=>w.pdfSheet=[id,type];
 w.saveCalls=0;w.guardarDados=async()=>{w.saveCalls++;if(w.failSave)throw Error('Servidor indisponível');};let seq=0;w.gerarId=()=>`new-${++seq}`;
 w._wsSairPara=id=>w.left=id;w.abrirVerOS=id=>w.opened=id;w._wsClienteAba=async(id,tab)=>{w._wsAbaAtual=tab;if(tab==='locais')await w.TGPassport.show(id)};w._wsMarcarOS=id=>w.marked=id;w._osPedirFoto=id=>w.photoOS=id;
 w.eval('const PACKS={express:{},expert:{},pro:{},supreme:{}};'+['packDoAdmin','moduloPassaporteAtivo'].map(name=>main.match(new RegExp('        function '+name+'\\([^]*?\\n        \\}'))[0]).join('\n'));
 w.eval(['_contratoLocalIds','_contratoAbrangeLocal','_contratoEquipamentos'].map(name=>main.match(new RegExp('        function '+name+'\\([^]*?\\n        \\}'))[0]).join('\n'));w.eval(moduleSource);return w;
}
const plain=v=>JSON.parse(JSON.stringify(v));const flush=()=>new Promise(r=>setTimeout(r,15));
test('equipment attribution excludes unowned headquarters, other tenants and other customers',()=>{const w=setup();try{const s=w.TGPassport.scope('c','l');assert.deepEqual(Array.from(w.TGPassport.equipment(s),e=>e.id),['e','shared']);assert.equal(w.TGPassport.scope('other','foreign'),null);assert.equal(w.TGPassport.scope('c','foreign'),null);assert.equal(w.TGPassport.equipment(w.TGPassport.scope('c')).length,0);w.contracts=false;assert.equal(w.TGPassport.equipment(s).length,0);w.dados.equipamentos.push({id:'direct',adminId:'a',clienteId:'c',localId:'l'});assert.deepEqual(Array.from(w.TGPassport.equipment(s),e=>e.id),['direct']);}finally{w.close()}});
test('employees consult assigned installations; clients and expired licenses cannot',()=>{const w=setup();try{w.usuarioLogado={id:'f',adminId:'a',role:'funcionario'};assert(w.TGPassport.scope('c','l'));assert(!w.TGPassport.scope('c'));assert(w.TGPassport.osButton(w.dados.servicos[0]).includes('Consultar instalação'));w.usuarioLogado.id='unassigned';assert(!w.TGPassport.scope('c','l'));w.usuarioLogado={id:'c',adminId:'a',role:'cliente'};assert(!w.TGPassport.scope('c','l'));w.usuarioLogado={id:'a',role:'admin'};w.licensed=false;assert(!w.TGPassport.scope('c','l'));}finally{w.close()}});
test('archive is read without mutation, tenant and customer are queried, opening adds a clean snapshot',async()=>{const w=setup();try{const before=JSON.stringify(w.dados);await w.TGPassport.open('c','l');assert.equal(JSON.stringify(w.dados),before);assert(w.document.body.textContent.includes('OLD-1'));assert(w.calls.some(c=>c[0]==='eq'&&c[1]==='admin_id'&&c[2]==='a'));assert(w.calls.some(c=>c[0]==='eq'&&c[1]==='cliente_id'&&c[2]==='c'));w.document.querySelector('[data-pp-action="view-os"][data-pp-id="old"]').click();assert.equal(w.opened,'old');assert.equal(w.saveCalls,0);const r=w.dados.servicos.find(x=>x.id==='old');assert.equal(w._snap.servicos.get('old'),JSON.stringify(w.M.servicos.to(r)));assert.deepEqual(plain(r.checklist),{OLD:true});}finally{w.close()}});
test('filters work without replacing the whole page and unsafe input never becomes markup or URL',async()=>{const w=setup();try{w.dados.equipamentos[0].fichaTecnica.nome='<img src=x onerror=bad>';w.dados.equipamentos[0].fichaTecnica.foto='javascript:alert(1)';await w.TGPassport.open('c','l');assert(!w.document.querySelector('img[src="x"]'));assert.equal(w.TGPassport.url('javascript:alert(1)'),'');assert.equal(w.TGPassport.url('data:image/svg+xml,test'),'');const input=w.document.querySelector('[data-pp-search]');input.value='192.168.1.3';input.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(w.document.querySelectorAll('.tg-pp-equipment-card').length,1);assert.equal(w.document.querySelector('[data-pp-search]'),input);input.value='none';input.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(w.document.querySelectorAll('.tg-pp-equipment-card').length,0);}finally{w.close()}});
test('saving site metadata retains unknown metadata, original addresses, OS and historical checklists',async()=>{const w=setup();try{w.dados.locais[0].passaporteTecnico.extension={a:1};const oldOS=JSON.stringify(w.dados.servicos);await w.TGPassport.open('c','l');w.document.querySelector('[data-pp-action="edit-site"]').click();const form=w.document.querySelector('[data-pp-editor] form');form.elements.armario.value='Armário novo';form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(w.dados.locais[0].passaporteTecnico.armario,'Armário novo');assert.deepEqual(plain(w.dados.locais[0].passaporteTecnico.extension),{a:1});assert.equal(w.dados.locais[0].morada,'Rua Armazém');assert.equal(JSON.stringify(w.dados.servicos),oldOS);assert.equal(w.saveCalls,1);assert(w.alerts.some(x=>x.includes('guardada')));}finally{w.close()}});
test('new equipment has explicit customer ownership, failed save retry does not duplicate it',async()=>{const w=setup();try{await w.TGPassport.open('c','l');w.document.querySelector('[data-pp-action="edit-equipment"]').click();const form=w.document.querySelector('[data-pp-editor] form');form.elements.nome.value='NVR 01';form.elements.ip.value='192.168.1.10';w.failSave=true;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await flush();assert(w.document.querySelector('[data-pp-save-status]').textContent.includes('Não foi possível'));const added=w.dados.equipamentos.find(x=>x.id==='new-1');assert.equal(added.clienteId,'c');assert.equal(added.localId,'l');const n=w.dados.equipamentos.length;w.failSave=false;form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(w.dados.equipamentos.length,n);assert.equal(w.saveCalls,2);}finally{w.close()}});
test('photo attachment delegates to existing OS handler',async()=>{const w=setup();try{await w.TGPassport.open('c','l');w.document.querySelector('[data-pp-action="photos"]').click();assert.equal(w.photoOS,'live');}finally{w.close()}});
test('late archive response cannot overwrite a different installation or revoked session',async()=>{const w=setup();try{let resolve;w._buscarPaginadoGenerico=()=>new Promise(r=>resolve=r);const pending=w.TGPassport.open('c','l');await flush();await w.TGPassport.show('c');resolve({data:w.archive});await pending;assert(w.document.body.textContent.includes('Conhecer o local antes de começar'));assert(!w.document.body.textContent.includes('OLD-1'));w.licensed=false;assert(!w.TGPassport.scope('c'));}finally{w.close()}});
test('archive failure reports incomplete history and offers retry',async()=>{const w=setup();try{w._buscarPaginadoGenerico=async()=>({error:Error('offline')});await w.TGPassport.open('c','l');assert(w.document.querySelector('.tg-pp-warning'));assert(w.document.querySelector('[data-pp-action="retry"]'));assert(w.document.body.textContent.includes('Avaria'));}finally{w.close()}});
test('mappers round-trip supplemental fields and omit absent fields for existing records',()=>{const w=setup();try{for(const [key,app,db] of [['clientes','passaporteTecnico','passaporte_tecnico'],['locais','passaporteTecnico','passaporte_tecnico'],['equipamentos','fichaTecnica','ficha_tecnica'],['servicos','passaporteIntervencao','passaporte_intervencao']]){const old={id:'x',admin_id:'a'},mapped=w.M[key].from(old);assert(!Object.hasOwn(w.M[key].to(mapped),db));const raw={...old,[db]:{unknown:'keep',nome:'Teste'}};assert.deepEqual(plain(w.M[key].to(w.M[key].from(raw))[db]),raw[db]);}assert.equal(w.M.equipamentos.to(w.M.equipamentos.from({id:'e',admin_id:'a',cliente_id:'c'})).cliente_id,'c');}finally{w.close()}});
test('existing history module and original history UI are preserved',()=>{assert.equal(fs.readFileSync('tg-client-history.js','utf8'),require('node:child_process').execFileSync('git',['show','HEAD:tg-client-history.js'],{encoding:'utf8'}));assert(main.includes("historico: 'Histórico'"));assert(main.includes("else if (aba === 'historico') await window.TGClientHistory.show(clienteId)"));assert(main.includes("locais: 'Instalações'"));assert(!main.match(/const WS_CLIENTE_ABAS =[^\n]+/)[0].includes("'passaporte'"));});

test('passport access follows the tenant pack for managers and employees, including direct links and downgrade',async()=>{const w=setup();try{
 const before=JSON.stringify(w.dados);
 for(const pack of ['express',null,'unknown']){w.admin.packAtual=pack;assert.equal(w.TGPassport.scope('c','l'),null);assert.equal(w.TGPassport.osButton(w.dados.servicos[0]),'');await w.TGPassport.open('c','l');assert.equal(w.calls.length,0);}
 for(const pack of ['expert','pro','supreme']){w.admin.packAtual=pack;assert(w.TGPassport.scope('c','l'));w.usuarioLogado={id:'f',adminId:'a',role:'funcionario'};assert(w.TGPassport.scope('c','l'));w.usuarioLogado={id:'a',role:'admin'};}
 await w.TGPassport.open('c','l');assert(w.document.querySelector('.tg-passport'));w.admin.packAtual='express';w.document.dispatchEvent(new w.Event('tg:interface-updated'));assert(!w.document.querySelector('.tg-passport'));assert.equal(JSON.stringify(w.dados),before);
}finally{w.close()}});
test('one installations tab exists for every pack, Express retains the simple list and premium opens passports',async()=>{const w=setup();try{
 w.adminAtual=()=>w.admin;w.escapeHtmlSimples=v=>String(v??'');
 w.eval(main.match(/        function _wsLocaisHtml\([^]*?\n        \}/)[0]);
 w.admin.packAtual='express';const simple=w._wsLocaisHtml('c');assert(simple.includes('Armazém'));assert(simple.includes('Adicionar instalação'));assert(!simple.includes('TGPassport.open'));
 for(const pack of ['expert','pro','supreme']){w.admin.packAtual=pack;assert(w._wsLocaisHtml('c').includes('TGPassport.open'));await w.TGPassport.show('c');assert(w.document.body.textContent.includes('Nova instalação'));assert(w.document.querySelectorAll('[data-pp-site]').length===2);}
}finally{w.close()}});
test('workspace renders one installations entry and preserves new/edit actions in premium packs',async()=>{const w=setup();try{
 w.adminAtual=()=>w.admin;w.escapeHtmlSimples=v=>String(v??'');w.moduloAssistAtivo=()=>false;w.moduloArmazemAtivo=()=>false;
 w.eval(main.match(/        const WS_CLIENTE_ABAS =[^\n]+/)[0]+main.match(/        const WS_CLIENTE_ABAS_LABEL =[^\n]+/)[0]+['_wsClienteAba','_wsLocaisHtml'].map(name=>main.match(new RegExp('        (?:async )?function '+name+'\\([^]*?\\n        \\}'))[0]).join('\n'));
 const overlay=w.document.getElementById('wsClienteOverlay');overlay.dataset.clienteAtual='';
 w.admin.packAtual='express';await w._wsClienteAba('c','locais');assert.equal(w.document.querySelectorAll('#wsClienteAbas button').length>0,true);assert.equal(w.document.getElementById('wsClienteAbas').textContent.split('Instalações').length,2);assert(!w.document.getElementById('wsClienteAbas').textContent.includes('Locais'));assert(!w.document.body.innerHTML.includes('TGPassport.open'));assert(w.document.body.textContent.includes('Nova instalação'));
 w.admin.packAtual='expert';await w._wsClienteAba('c','passaporte');assert.equal(w._wsAbaAtual,'locais');assert.equal(w.document.querySelectorAll('[data-pp-site]').length,2);
 w.abrirModalNovoLocalCliente=id=>w.createdFor=id;w.abrirModalLocalCliente=(id,localId)=>w.edited=[id,localId];w.abrirModal=(kind,id)=>w.edited=[kind,id];
 w.document.querySelector('[data-pp-action="new-site"]').click();assert.equal(w.createdFor,'c');
 w.document.querySelector('[data-pp-action="edit-address"][data-pp-id="l"]').click();assert.deepEqual(w.edited,['c','l']);
 w.document.querySelector('[data-pp-action="edit-address"]:not([data-pp-id])').click();assert.deepEqual(w.edited,['cliente','c']);
 w.document.querySelector('[data-pp-site="l"]').click();await flush();assert(w.document.body.textContent.includes('Piso 0'));
}finally{w.close()}});
test('deletion requires exact typed APAGAR, checks ownership and retains associated history',async()=>{const w=setup();try{
 w.admin.id='a';w.renderizarTudo=()=>{};w._wsClienteAba=async()=>{};
 w.eval(main.match(/        async function eliminarLocalCliente\([^]*?\n        \}/)[0]);
 const before=JSON.stringify(w.dados);let prompts=0;w.prompt=()=>{prompts++;return 'APAGAR'};
 assert.equal(await w.eliminarLocalCliente('foreign','other'),false);assert.equal(prompts,0);
 w.usuarioLogado={id:'f',adminId:'a',role:'funcionario'};assert.equal(await w.eliminarLocalCliente('l','c'),false);assert.equal(prompts,0);w.usuarioLogado={id:'a',role:'admin'};
 for(const answer of [null,'','apagar','APAGA',' APAGAR ']){w.prompt=()=>answer;assert.equal(await w.eliminarLocalCliente('l','c'),false);assert.equal(JSON.stringify(w.dados),before);assert.equal(w.saveCalls,0);}
 w.dados.relatoriosEspecialidade=[{id:'report',adminId:'a',clienteId:'c',localId:'l',texto:'Histórico original'}];
 w.prompt=message=>{assert(message.includes('APAGAR'));assert(message.includes('Armazém'));return 'APAGAR'};
 assert.equal(await w.eliminarLocalCliente('l','c'),true);assert(!w.dados.locais.some(l=>l.id==='l'));assert(w.dados.locais.some(l=>l.id==='foreign'));assert.equal(w.dados.servicos.length,1);assert.equal(w.dados.servicos[0].localId,null);assert.equal(w.dados.servicos[0].descricao,'Avaria');assert.deepEqual(plain(w.dados.servicos[0].checklist),{A:true});assert.equal(w.dados.relatoriosEspecialidade[0].texto,'Histórico original');assert.equal(w.dados.relatoriosEspecialidade[0].localId,null);assert.equal(w.saveCalls,1);
}finally{w.close()}});
test('delete controls exist in Express and premium lists, without offering to delete the Sede',async()=>{const w=setup();try{
 w.adminAtual=()=>w.admin;w.escapeHtmlSimples=v=>String(v??'');w.eval(main.match(/        function _wsLocaisHtml\([^]*?\n        \}/)[0]);
 w.admin.packAtual='express';assert(w._wsLocaisHtml('c').includes("eliminarLocalCliente('l','c')"));assert(!w._wsLocaisHtml('c').includes("eliminarLocalCliente('sede'"));
 w.admin.packAtual='expert';await w.TGPassport.show('c');const buttons=w.document.querySelectorAll('[data-pp-action="delete-site"]');assert.equal(buttons.length,1);assert.equal(buttons[0].dataset.ppId,'l');
 w.eliminarLocalCliente=async(id,cid)=>{w.deleted=[id,cid]};buttons[0].click();await flush();assert.deepEqual(w.deleted,['l','c']);
}finally{w.close()}});
test('passport opens the original archived OS work sheet and exports its existing PDF without writing a second report',async()=>{const w=setup();try{
 w.dados.servicos[0].passaporteIntervencao={trabalho:'Nota antiga preservada'};
 w.archiveSheets=[{id:'sheet-old',admin_id:'a',servico_id:'old',data:'2020-01-01',descricao:'Trabalho real da OS',materiais:'Cabo',horas_trabalhadas:2,assinatura:'assinatura-original'},{id:'foreign-sheet',admin_id:'b',servico_id:'old'}];
 await w.TGPassport.open('c','l');assert(!w.document.body.textContent.includes('Relatório técnico'));assert(w.document.body.textContent.includes('Folha de obra'));
 w.document.querySelector('[data-pp-action="work-sheet"][data-pp-id="old"]').click();await flush();assert.equal(w.openedSheet,'sheet-old');assert.equal(w.saveCalls,0);assert(w.calls.some(x=>x[0]==='eq'&&x[1]==='servico_id'&&x[2]==='old'));assert.equal(w.dados.folhasObra.length,1);assert.equal(w.dados.folhasObra[0].assinatura,'assinatura-original');assert.equal(w._snap.folhasObra.get('sheet-old'),JSON.stringify(w.M.folhasObra.to(w.dados.folhasObra[0])));assert.equal(w.dados.servicos[0].passaporteIntervencao.trabalho,'Nota antiga preservada');
 await w.TGPassport.open('c','l');w.document.querySelector('[data-pp-action="work-sheet-pdf"][data-pp-id="old"]').click();await flush();assert.deepEqual(w.pdfSheet,['sheet-old','cliente']);assert.equal(w.saveCalls,0);
}finally{w.close()}});
test('multiple OS work sheets can be selected, only sheets for this OS and tenant are listed',async()=>{const w=setup();try{
 w.archiveSheets=[{id:'s1',admin_id:'a',servico_id:'live',data:'2026-10-01',descricao:'Primeira visita'},{id:'s2',admin_id:'a',servico_id:'live',data:'2026-10-02',descricao:'Segunda visita'},{id:'other-os',admin_id:'a',servico_id:'unrelated',descricao:'SEGREDO'}];await w.TGPassport.open('c','l');w.document.querySelector('[data-pp-action="work-sheet"][data-pp-id="live"]').click();await flush();assert.equal(w.openedSheet,undefined);assert(w.document.body.textContent.includes('Primeira visita'));assert(w.document.body.textContent.includes('Segunda visita'));assert(!w.document.body.textContent.includes('SEGREDO'));w.document.querySelector('[data-pp-action="open-sheet"][data-pp-id="s1"]').click();await flush();assert.equal(w.openedSheet,'s1');assert.equal(w.saveCalls,0);
}finally{w.close()}});
test('missing work sheet is explicit; query failures and revoked access never open a false report',async()=>{const w=setup();try{
 await w.TGPassport.open('c','l');w.document.querySelector('[data-pp-action="work-sheet"][data-pp-id="live"]').click();await flush();assert(w.document.body.textContent.includes('Ainda não existe uma folha de obra'));assert.equal(w.saveCalls,0);assert.equal(w.openedSheet,undefined);
 w._buscarPaginadoGenerico=async()=>({error:Error('offline')});w.document.querySelector('[data-pp-action="work-sheet"][data-pp-id="live"]').click();await flush();assert(w.document.querySelector('[data-pp-editor] .tg-pp-warning'));assert(!w.document.querySelector('[data-pp-editor]').textContent.includes('Ainda não existe'));
 let resolve;w._buscarPaginadoGenerico=()=>new Promise(r=>resolve=r);w.document.querySelector('[data-pp-action="work-sheet"][data-pp-id="live"]').click();await flush();w.admin.packAtual='express';resolve({data:[{id:'late',admin_id:'a',servico_id:'live'}]});await flush();assert.equal(w.openedSheet,undefined);assert.equal((w.dados.folhasObra||[]).length,0);
}finally{w.close()}});
test('a shared contract opens from each covered passport and unlocated equipment remains at the primary site',async()=>{const w=setup();try{
 w.dados.locais.push({id:'second',adminId:'a',clienteId:'c',nome:'Segunda instalação'});w.dados.contratos[0].locaisIds=['l','second'];w.dados.contratos[0].numero='CT-MULTI';w.dados.contratos[0].documentoUrl='https://example.com/contract.pdf';w.dados.contratos[0].documentoNome='Condições CT-MULTI';
 w._wsSairPara=()=>{};w.abrirModalContrato=id=>w.openedContract=id;
 await w.TGPassport.open('c','second');assert(w.document.body.textContent.includes('CT-MULTI'));assert(w.document.body.textContent.includes('Condições CT-MULTI'));assert(!w.TGPassport.equipment(w.TGPassport.scope('c','second')).some(e=>e.id==='shared'));
 w.document.querySelector('[data-pp-action="contract"]').click();assert.equal(w.openedContract,w.dados.contratos[0].id);
 await w.TGPassport.open('c','l');assert(w.document.querySelector('[data-pp-action="contract"]'));
 w.moduloContratosAtivo=()=>false;await w.TGPassport.open('c','l');assert(!w.document.querySelector('[data-pp-action="contract"]'));assert(!w.document.body.textContent.includes('Condições CT-MULTI'));
}finally{w.close()}});
