const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');
const src=fs.readFileSync(require('node:path').join(__dirname,'../app-principal.js'),'utf8');
function setup(n){const dom=new JSDOM('<body></body>',{runScripts:'outside-only'}),w=dom.window;w.eval(`var usuarioLogado={role:'cliente',clienteId:'c1',adminId:'a1'};var dados={clientes:[{id:'c1',adminId:'a1',morada:'Rua da sede'}],locais:[],servicos:[]};function escapeHtmlSimples(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')}function gerarId(){return 'p'+Math.random()}function getDataHoje(){return '2026-10-02'}function guardarDados(){return Promise.resolve()}function _notificarAdminESubadmin(){}function _clienteLabel(){return 'Cliente'}function renderizarPortalCliente(){}function alert(){}`);w.dados.locais=Array.from({length:n},(_,i)=>({id:'l'+i,clienteId:'c1',adminId:'a1',nome:'Loja '+i,morada:'Rua '+i}));w.dados.locais.push({id:'foreign',clienteId:'other',adminId:'a1',nome:'Outro cliente'});w.eval(src.slice(src.indexOf('        function _portalAssistCliente()'),src.indexOf('        function renderizarAuditoria()')));return w;}
test('single location selected; multiple require choice; foreign locations excluded',()=>{for(const n of [0,1,2]){const w=setup(n);w.portalPedirAssistencia();const s=w.document.getElementById('portalAjudaLocal');assert.equal(s.value,n===0?'__sede_cliente__':'');assert.equal(s.disabled,n===0);assert.ok(!s.textContent.includes('Outro cliente'));assert.equal(w.document.getElementById('portalAjudaEnviar').disabled,false);w.close();}});
test('required urgency/problem, persistence and no double submission',async()=>{const w=setup(2);w.portalPedirAssistencia();const d=w.document;d.getElementById('portalAjudaLocal').value='l1';d.getElementById('portalAjudaDesc').value='Sensor avariado';await w.portalEnviarAssistencia();assert.equal(w.dados.servicos.length,0);d.getElementById('portalAjudaUrgencia').value='alta';await Promise.all([w.portalEnviarAssistencia(),w.portalEnviarAssistencia()]);assert.equal(w.dados.servicos.length,1);const p=w.dados.servicos[0];assert.equal(p.localId,'l1');assert.equal(p.morada,'Rua 1');assert.match(p.descricao,/Urgência: Alta/);assert.match(p.descricao,/Sensor avariado/);assert.equal(p.status,'por aprovar');w.close();});
test('changed session cannot submit old form',async()=>{const w=setup(1);w.portalPedirAssistencia();w.usuarioLogado.clienteId='other';await w.portalEnviarAssistencia();assert.equal(w.dados.servicos.length,0);w.close();});

test('headquarters is selectable with installations and saves client address without a fake location FK',async()=>{const w=setup(1);w.portalPedirAssistencia();const d=w.document;assert.equal(d.getElementById('portalAjudaLocal').options.length,3);d.getElementById('portalAjudaLocal').value='__sede_cliente__';d.getElementById('portalAjudaUrgencia').value='normal';d.getElementById('portalAjudaDesc').value='Avaria na sede';await w.portalEnviarAssistencia();assert.equal(w.dados.servicos[0].localId,null);assert.equal(w.dados.servicos[0].morada,'Rua da sede');assert.match(w.dados.servicos[0].descricao,/Local: Sede/);w.close();});
test('installation cards include headquarters address and all published reports with worksheets',()=>{const w=setup(1);w.eval(`const TIPOS_ESPECIALIDADE=[];function _dataCorteMeses(){return '2025-10-02'}function _portalFolhaVisivel(){return true}`);w.dados.servicos=[{id:'s1',adminId:'a1',clienteId:'c1',localId:null,descricao:'Trabalho sede',status:'concluído',data:'2026-09-01'},{id:'s2',adminId:'a1',clienteId:'c1',localId:'l0',descricao:'Trabalho loja',data:'2026-09-01'}];w.dados.folhasObra=[{id:'f1',servicoId:'s1',descricao:'Folha'}];w.dados.relatoriosEspecialidade=[{id:'r1',servicoId:'s1',tipo:'Personalizado',adminId:'a1',clienteId:'c1'},{id:'r2',servicoId:'s1',tipo:'Rascunho',rascunho:true},{id:'r3',servicoId:'s1',tipo:'Outro tenant',adminId:'a2'}];w.eval(src.slice(src.indexOf('        function _gerarHTMLIntervencoesPorLocal('),src.indexOf('        async function _historicoCarregarMaisAntigo')));const html=w._gerarHTMLIntervencoesPorLocal('c1',true,'2025-10-02','portal-acc-locais');w.document.body.innerHTML=html;const cards=w.document.querySelectorAll('details');assert.equal(cards.length,2);assert.match(cards[0].textContent,/Rua da sede/);assert.match(cards[0].textContent,/Personalizado/);assert.match(cards[0].textContent,/Folha de obra/);assert.ok(!html.includes('Rascunho'));assert.ok(!html.includes('Outro tenant'));assert.match(cards[1].textContent,/Trabalho loja/);assert.ok(!cards[0].textContent.includes('Trabalho loja'));w.close();});
