import { SMTPClient } from "https://deno.land/x/denomailer@1.6.0/mod.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const COR_NAVY = "#0b3b5c";
const COR_TEAL = "#1a5f7a";
const COR_LARANJA = "#f4520e";
function json(obj, status = 200) { return new Response(JSON.stringify(obj), { status, headers: { ...cors, "Content-Type": "application/json" } }); }
function minificarHtml(html) { return html.split("\n").map((linha) => linha.trim()).join("").replace(/>\s+</g, "><"); }
function escapeHtml(s) { return String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])); }
function semAcentosAssunto(s) { return String(s ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^\x00-\x7F]/g, ""); }
// Etiqueta pequena "(IVA Inc.)" a juntar a valores monetários mostrados nos emails — mesma
// ideia (e mesmo texto) já usada na app, para nunca ficar ambíguo se o preço já inclui IVA.
// Uso: passar notaPequena:true numa linha do infoCard(), ou chamar comIva(valorTexto) direto
// num sítio que não passa por infoCard (ex.: a lista de itens do pedido consolidado).
const IVA_INC_HTML = ' <span style="font-size:11px;color:#94a3b8;font-weight:400;">(IVA Inc.)</span>';
function comIva(valorTexto) { return `${escapeHtml(valorTexto)}${IVA_INC_HTML}`; }
function infoCard(linhas) {
  const linhasHtml = linhas.filter((l) => l && l.valor != null && l.valor !== "").map((l, i, arr) => `<tr><td style="padding:11px 4px;${i < arr.length - 1 ? "border-bottom:1px solid #e8edf3;" : ""}color:#64748b;font-size:13px;">${escapeHtml(l.rotulo)}</td><td style="padding:11px 4px;${i < arr.length - 1 ? "border-bottom:1px solid #e8edf3;" : ""}text-align:right;font-weight:700;font-size:${l.grande ? "17px" : "14px"};color:${l.destaque ? COR_LARANJA : "#0f172a"};">${escapeHtml(l.valor)}${l.notaPequena ? IVA_INC_HTML : ""}</td></tr>`).join("");
  return `<table style="width:100%;border-collapse:collapse;background:#f8fafc;border-radius:12px;padding:4px 16px;margin:18px 0;">${linhasHtml}</table>`;
}
function botaoCTA(texto, url) { return `<table role="presentation" style="margin:26px auto;" cellpadding="0" cellspacing="0"><tr><td style="border-radius:10px;background:${COR_LARANJA};"><a href="${escapeHtml(url)}" style="display:inline-block;padding:15px 32px;color:#fff;font-weight:700;font-size:15px;text-decoration:none;border-radius:10px;">${escapeHtml(texto)}</a></td></tr></table><p style="font-size:12px;color:#526079;line-height:1.6;">Se o botão não funcionar, abra este link:<br><a href="${escapeHtml(url)}" style="color:#152a52;word-break:break-all;">${escapeHtml(url)}</a></p>`; }
function avisoBox(texto, tipo) {
  const cores = { laranja:{bg:"#fff7ed",borda:"#fdba74",texto:"#9a3412"}, vermelho:{bg:"#fef2f2",borda:"#fca5a5",texto:"#991b1b"}, verde:{bg:"#f0fdf4",borda:"#86efac",texto:"#166534"}, azul:{bg:"#f0f9fb",borda:"#7dd3e0",texto:"#0e7490"} }[tipo] || {bg:"#f8fafc",borda:"#e2e8f0",texto:"#334155"};
  return `<div style="background:${cores.bg};border:1px solid ${cores.borda};border-radius:10px;padding:14px 16px;margin:16px 0;color:${cores.texto};font-size:13px;line-height:1.6;">${texto}</div>`;
}
function wrapper(plataforma, logoUrl, conteudoHtml, titulo = "A sua conta Total Gest") {
  return `<!doctype html><html lang="pt-PT"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(titulo)}</title></head><body style="margin:0;padding:0;background:#f1f4f8;font-family:Arial,Helvetica,sans-serif;color:#24334b;">
<div style="display:none;max-height:0;overflow:hidden;mso-hide:all;">${escapeHtml(titulo)} — ${escapeHtml(plataforma)}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f1f4f8;"><tr><td align="center" style="padding:32px 12px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#fff;border:1px solid #dfe5ed;border-radius:16px;overflow:hidden;">
<tr><td style="padding:26px 28px;background:#152a52;border-bottom:4px solid #f97316;">${logoUrl ? `<img src="${escapeHtml(logoUrl)}" alt="" width="56" height="56" style="display:block;border:0;background:#fff;border-radius:8px;margin-bottom:12px;">` : ""}<span style="color:#fff;font-size:23px;font-weight:bold;letter-spacing:1px;">${escapeHtml(plataforma)}</span><p style="color:#d5dfef;font-size:12px;margin:8px 0 0;">Gestão que gera resultados.</p></td></tr>
<tr><td style="padding:30px 24px 24px;font-size:15px;line-height:1.7;overflow-wrap:anywhere;word-break:break-word;"><h1 style="font-size:24px;line-height:1.25;color:#152a52;margin:0 0 24px;">${escapeHtml(titulo)}</h1>${conteudoHtml}</td></tr>
<tr><td style="padding:22px 24px;background:#f8fafc;border-top:1px solid #e2e8f0;font-size:12px;line-height:1.7;color:#526079;">Precisa de ajuda? <a href="mailto:totalgestpro@gmail.com" style="color:#152a52;font-weight:bold;">Fale com a Total Gest</a>.<br><a href="tel:+351939373322" style="color:#526079;">+351 939 373 322</a> · Chamada para a rede móvel nacional.<br><span style="font-size:11px;">Mensagem automática relativa à sua conta ou aos seus serviços.</span></td></tr>
</table></td></tr></table></body></html>`;
}
function montarEmail(tipo, p) {
  const plataforma = p.plataforma || "Total Gest";
  const titulos = { pagamento:"Dados para pagamento", boas_vindas_demo:"Bem-vindo à Total Gest", renovacao:"A sua licença está a terminar", vencida:"A sua licença expirou", renovacao_aprovada:"Renovação aprovada", pedido_renovacao_consolidado:"Novo pedido de renovação", boas_vindas_equipa:"Bem-vindo à sua equipa", aviso_novo_trial:"Novo pedido de demonstração", confirmar_trial:"Confirme a sua conta", definir_password_trial:"Defina a sua palavra-passe", recuperar_password:"Recuperar a sua palavra-passe", cancelamento_licenca:"Pedido de cancelamento recebido", cancelamento_licenca_interno:"Novo pedido de cancelamento", lembrete_pagamento:"Lembrete de pagamento" };
  const render = (brand, logo, content) => wrapper(brand, logo, content, titulos[tipo] || "A sua conta Total Gest");
  const nome = (p.to_name || "").split(" ")[0] || "";
  if (tipo === "pagamento") {
    const ehRenovacao=p.contexto==="renovacao", ehAtivacao=p.contexto==="ativacao", ehAddon=p.contexto==="compra_addon";
    const intro=ehRenovacao?`<p>Recebemos o teu pedido de renovação na <strong>${escapeHtml(plataforma)}</strong>. Segue o resumo e as instruções de pagamento para ativarmos assim que possível.</p>`:ehAtivacao?`<p>Recebemos o teu pedido de ativação de conta na <strong>${escapeHtml(plataforma)}</strong>. Segue o resumo e as instruções de pagamento para podermos ativar a sua conta assim que possível.</p>`:ehAddon?`<p>Recebemos o teu pedido de um novo módulo na <strong>${escapeHtml(plataforma)}</strong>. Segue o resumo e as instruções de pagamento para ativarmos assim que possível.</p>`:`<p>Bem-vindo(a) à <strong>${escapeHtml(plataforma)}</strong>! Segue o resumo da sua licença e as instruções de pagamento para ativarmos o seu acesso.</p>`;
    const fecho=(ehRenovacao||ehAtivacao||ehAddon)?`<p>Assim que confirmarmos o pagamento, o módulo/conta fica ativo e recebe um email de confirmação.</p>`:`<p>Obrigado por confiar em nós.</p>`;
    const mbwayBloco=p.mbway&&String(p.mbway).trim()?avisoBox(`<strong style="color:#c2410c;">Ou, se preferir, pague por MB WAY</strong><br/>Envie o pagamento para o número <strong>${escapeHtml(p.mbway)}</strong> e indique o seu nome/empresa na referência.`,"laranja"):"";
    const conteudo=`<p>Olá ${escapeHtml(nome)},</p>${intro}${infoCard([{rotulo:"Empresa",valor:p.empresa},{rotulo:"Licença",valor:p.licenca},{rotulo:"Valor",valor:p.valor,grande:true,notaPequena:true},{rotulo:"Referência",valor:p.referencia,grande:true,destaque:true}])}<div style="background:#f0f9fb;border-radius:12px;padding:18px 18px 14px;margin:18px 0;"><p style="margin:0 0 10px;font-weight:800;color:${COR_TEAL};font-size:13px;text-transform:uppercase;letter-spacing:.4px;">Dados para pagamento por transferência</p><p>Titular: <strong>${escapeHtml(p.titular)}</strong></p><p>IBAN: <strong>${escapeHtml(p.iban)}</strong></p><p>Banco: <strong>${escapeHtml(p.banco)}</strong></p>${p.swift?`<p>BIC/SWIFT: <strong>${escapeHtml(p.swift)}</strong></p>`:""}${p.instrucoes?`<p>${escapeHtml(p.instrucoes)}</p>`:""}</div>${mbwayBloco}${fecho}`;
    const assunto=ehRenovacao?`Pedido de renovacao - dados de pagamento`:ehAtivacao?`Pedido de ativacao - dados de pagamento`:ehAddon?`Pedido de novo modulo - dados de pagamento`:`Bem-vindo a ${semAcentosAssunto(plataforma)} - Licenca e dados de pagamento`;
    return {subject:assunto,html:render(plataforma,p.logo_url,conteudo)};
  }
  if (tipo === "boas_vindas_demo") {
    const dias=p.dias||"14";
    const conteudo=`<p>Olá ${escapeHtml(nome)},</p><p>Bem-vindo(a) à <strong>${escapeHtml(plataforma)}</strong>! A sua conta de demonstração já está pronta a usar.</p>${infoCard([{rotulo:"Empresa",valor:p.empresa},{rotulo:"Licença",valor:p.licenca},{rotulo:"Duração",valor:`${dias} dia(s)`}])}${avisoBox(`<strong>✓ Sem qualquer custo</strong> — não é necessário nenhum pagamento durante o período de demonstração.`,"verde")}<p>Pode iniciar sessão com o email e a password que lhe foram atribuídos e explorar a plataforma à vontade.</p><p>Se tiver alguma dúvida, estamos disponíveis para ajudar.</p><p>Bem-vindo(a)!</p>`;
    return {subject:`Bem-vindo a ${semAcentosAssunto(plataforma)} - Conta demo ativada`,html:render(plataforma,p.logo_url,conteudo)};
  }
  if (tipo === "renovacao") { const c=`<p>Olá ${escapeHtml(nome)},</p><p>A licença da <strong>${escapeHtml(p.empresa)}</strong> (plano <strong>${escapeHtml(p.plano)}</strong>) expira em <strong>${escapeHtml(p.dias)} dia(s)</strong>, a ${escapeHtml(p.data_expiracao)}.</p>${p.link_renovacao?`${botaoCTA("Gerir a minha licença",p.link_renovacao)}<p style="color:#64748b;font-size:12px;text-align:center;">Pode renovar o mesmo plano, escolher outro plano (com ou sem add-ons), ou cancelar a subscrição — sem precisar de fazer login. Este link é válido durante 30 dias.</p>`:`<p>Para evitar interrupções no acesso, entra na aplicação e vai a <strong>"Minha Licença"</strong> para pedir a renovação.</p>`}`; return {subject:`A tua licenca expira em ${p.dias} dia(s)`,html:render(plataforma,p.logo_url,c)}; }
  if (tipo === "vencida") { const c=`<p>Olá ${escapeHtml(nome)},</p><p>A licença da <strong>${escapeHtml(p.empresa)}</strong> (plano <strong>${escapeHtml(p.plano)}</strong>) expirou a <strong>${escapeHtml(p.data_expiracao)}</strong>.</p><p>O acesso à aplicação está agora limitado a "Relatório de Assiduidade" e "Minha Licença" para admins, e só à picagem de ponto para funcionários.</p>${p.link_renovacao?`${botaoCTA("Gerir a minha licença",p.link_renovacao)}<p style="color:#64748b;font-size:12px;text-align:center;">Pode renovar o mesmo plano, escolher outro plano (com ou sem add-ons), ou cancelar a subscrição — sem precisar de fazer login. Este link é válido durante 30 dias.</p>`:`<p>Entra em <strong>"Minha Licença"</strong> para renovar e restaurar o acesso completo.</p>`}`; return {subject:`A tua licenca expirou - acesso limitado`,html:render(plataforma,p.logo_url,c)}; }
  if (tipo === "renovacao_aprovada") { const c=`<p>Olá ${escapeHtml(nome)},</p><p>O teu pedido de renovação foi aprovado! ✅</p>${infoCard([{rotulo:"Licença atualizada",valor:p.licenca,grande:true}])}<p>Já podes continuar a usar a ${escapeHtml(plataforma)} sem restrições.</p>`; return {subject:`Renovacao aprovada - ${semAcentosAssunto(p.licenca)}`,html:render(plataforma,p.logo_url,c)}; }
  if (tipo === "pedido_renovacao_consolidado") { const itensHtml=(Array.isArray(p.itens)?p.itens:[]).map(txt=>`<li>${comIva(txt)}</li>`).join(""); const c=`<p>Novo pedido de <strong>renovação consolidada</strong>.</p>${infoCard([{rotulo:"Empresa",valor:p.empresa},{rotulo:"Responsável",valor:p.adminNome},{rotulo:"Periodicidade",valor:p.periodo==="anual"?"Anual":"Mensal"}])}<ul>${itensHtml}</ul>${infoCard([{rotulo:"Total do pedido",valor:p.total?`${p.total} €`:"—",grande:true,destaque:true,notaPequena:!!p.total}])}${p.observacao?`<p><strong>Observação do cliente:</strong> ${escapeHtml(p.observacao)}</p>`:""}`; return {subject:`Pedido de renovacao consolidado - ${semAcentosAssunto(p.empresa||p.adminNome||"")}`,html:render(plataforma,p.logo_url,c)}; }
  if (tipo === "boas_vindas_equipa") { const temLink=!!(p.link_confirmacao&&String(p.link_confirmacao).trim()); const c=`<p>Olá ${escapeHtml(nome)},</p><p>A tua conta na <strong>${escapeHtml(plataforma)}</strong> foi criada! ${temLink?"Falta só confirmares a tua conta para poderes entrar com o teu email e a password que te foi definida.":"Já podes entrar com o teu email e a password que te foi definida."}</p>${p.empresa?infoCard([{rotulo:"Empresa",valor:p.empresa}]):""}${temLink?`${botaoCTA("Confirmar a minha conta",p.link_confirmacao)}<p style="color:#b45309;font-size:12px;font-weight:700;text-align:center;">⏱️ Confirma dentro de 48 horas — depois disso a conta é removida automaticamente e terás de pedir uma nova ao teu administrador.</p>`:""}<p>Se tiveres alguma dúvida, fala com o teu administrador.</p><p>Bem-vindo(a)!</p>`; return {subject:`Bem-vindo a ${semAcentosAssunto(plataforma)}${temLink?" - confirma a tua conta":""}`,html:render(plataforma,p.logo_url,c)}; }
  if (tipo === "aviso_novo_trial") { const c=`<p>Nova inscrição no trial de 14 dias da <strong>${escapeHtml(plataforma)}</strong>.</p>${infoCard([{rotulo:"Empresa",valor:p.empresa},{rotulo:"Nome",valor:p.nome},{rotulo:"Email",valor:p.email_lead},{rotulo:"Telefone",valor:p.telefone||"—"},{rotulo:"Nº colaboradores",valor:p.colaboradores||"—"},{rotulo:"NIF",valor:p.nif||"—"},{rotulo:"IP",valor:p.ip||"—"}])}<p style="color:#64748b;font-size:12px;">A conta só fica realmente ativa depois de a pessoa confirmar o email — isto é só um aviso do pedido, ainda por confirmar.</p>`; return {subject:`Novo pedido de trial - ${semAcentosAssunto(p.empresa||"")}`,html:render(plataforma,p.logo_url,c)}; }
  if (tipo === "confirmar_trial") { const c=`<p>Olá ${escapeHtml(nome)},</p><p>Falta só um passo para começar o seu teste gratuito de 14 dias na <strong>${escapeHtml(plataforma)}</strong>.</p>${botaoCTA("Confirmar e ativar conta",p.link_confirmacao)}<p style="color:#b45309;font-size:12px;font-weight:700;text-align:center;">⏱️ Este link é válido durante 48 horas. Depois disso terá de fazer o pedido novamente.</p><p style="color:#64748b;font-size:12px;">Se não pediu esta conta, pode ignorar este email.</p>`; return {subject:`Confirme a sua conta ${semAcentosAssunto(plataforma)} - 14 dias gratis`,html:render(plataforma,p.logo_url,c)}; }
  if (tipo === "definir_password_trial") { const c=`<p>Olá ${escapeHtml(nome)},</p><p>A sua conta <strong>${escapeHtml(plataforma)}</strong>${p.empresa?` (${escapeHtml(p.empresa)})`:""} já está ativa! Falta só definir a sua password de acesso.</p>${botaoCTA("Definir password e entrar",p.link_confirmacao)}<p style="color:#64748b;font-size:12px;">Se não pediu esta conta, pode ignorar este email.</p>`; return {subject:`Defina a sua password - ${semAcentosAssunto(plataforma)}`,html:render(plataforma,p.logo_url,c)}; }
  if (tipo === "recuperar_password") { const c=`<p>Olá${nome?" "+escapeHtml(nome):""},</p><p>Recebemos um pedido para redefinir a password da sua conta <strong>${escapeHtml(plataforma)}</strong>${p.empresa?` (${escapeHtml(p.empresa)})`:""}.</p>${botaoCTA("Definir nova password",p.link_confirmacao)}<p style="color:#64748b;font-size:12px;">Se não pediu esta alteração, pode ignorar este email — a sua password atual continua a funcionar normalmente.</p>`; return {subject:`Recuperar password - ${semAcentosAssunto(plataforma)}`,html:render(plataforma,p.logo_url,c)}; }
  if (tipo === "cancelamento_licenca" || tipo === "cancelamento_licenca_interno") { const c=`<p>${tipo==="cancelamento_licenca"?`Olá ${escapeHtml(nome)}, confirmamos que recebemos o pedido de encerramento.`:`${escapeHtml(p.to_name||"-")} (${escapeHtml(p.empresa||"-")}) solicitou o encerramento do acordo.`}</p>${infoCard([{rotulo:"Assinado por",valor:p.assinatura_nome},{rotulo:"Data da assinatura",valor:p.data_assinatura},{rotulo:"Prazo para recolha de dados",valor:p.prazo_recolha}])}${p.mensagem?`<p>${escapeHtml(p.mensagem)}</p>`:""}`; return {subject:tipo==="cancelamento_licenca"?`Confirmacao de cancelamento - ${semAcentosAssunto(p.empresa||plataforma)}`:`[Cancelamento] ${semAcentosAssunto(p.empresa||p.to_name||"Cliente")} pediu encerramento do acordo`,html:render(plataforma,p.logo_url,c)}; }
  if (tipo === "lembrete_pagamento") { const c=`<p>Olá ${escapeHtml(nome)},</p><p>Este é um lembrete de que o pagamento da sua licença <strong>${escapeHtml(plataforma)}</strong>${p.empresa?` (${escapeHtml(p.empresa)})`:""} ainda não foi confirmado do nosso lado.</p>${avisoBox(`<strong>⏱️ Por favor, efetue o pagamento no prazo máximo de 48 horas.</strong>`,"vermelho")}${p.valor?infoCard([{rotulo:"Valor",valor:p.valor,grande:true,notaPequena:true},{rotulo:"IBAN",valor:p.iban},{rotulo:"MB WAY",valor:p.mbway}]):""}<p style="color:#64748b;font-size:13px;"><strong>Se já efetuou o pagamento</strong>, pode ignorar esta mensagem.</p>`; return {subject:`Lembrete de pagamento - ${semAcentosAssunto(plataforma)}`,html:render(plataforma,p.logo_url,c)}; }
  return null;
}
Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  try {
    const GMAIL_USER=Deno.env.get("GMAIL_USER"), GMAIL_APP_PASSWORD=Deno.env.get("GMAIL_APP_PASSWORD");
    if (!GMAIL_USER || !GMAIL_APP_PASSWORD) return json({erro:"GMAIL_USER / GMAIL_APP_PASSWORD não configurados nos secrets da função."},500);
    const body=await req.json().catch(()=>({})); const {tipo,to_email}=body;
    if (!tipo || !to_email) return json({erro:"Faltam dados (tipo, to_email)."},400);
    if (tipo==="pagamento" || tipo==="lembrete_pagamento") { try { const SUPABASE_URL=Deno.env.get("SUPABASE_URL"), SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); const service=createClient(SUPABASE_URL,SERVICE_KEY); const {data}=await service.from("administradores").select("dados_bancarios").eq("id","superadmin").maybeSingle(); const db=data?.dados_bancarios||{}; Object.assign(body,{titular:db.titular||"",iban:db.iban||"(a definir)",banco:db.banco||"",swift:db.swift||"",mbway:db.mbway||"",instrucoes:db.instrucoes||""}); } catch(e){ console.error("Erro ao buscar dados bancários:",e); } }
    const email=montarEmail(tipo,body); if (!email) return json({erro:"Tipo de email desconhecido: "+tipo},400);
    const client=new SMTPClient({connection:{hostname:"smtp.gmail.com",port:465,tls:true,auth:{username:GMAIL_USER,password:GMAIL_APP_PASSWORD}}});
    await client.send({from:`Total Gest <${GMAIL_USER}>`,to:to_email,subject:email.subject,content:"auto",html:minificarHtml(email.html)}); await client.close(); return json({ok:true});
  } catch(e){ console.error("Erro ao enviar email:",e); return json({erro:String(e)},500); }
});
